// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package thread_list_params

type ThreadListParams struct {
	// Optional archived filter; when set to true, only archived threads are returned.
	// If false or null, only non-archived threads are returned.
	Archived ThreadListParamsArchived `json:"archived,omitempty"`

	// Opaque pagination cursor returned by a previous call.
	Cursor ThreadListParamsCursor `json:"cursor,omitempty"`

	// Optional cwd filter; when set, only threads whose session cwd exactly matches
	// this path are returned.
	Cwd ThreadListParamsCwd `json:"cwd,omitempty"`

	// Optional page size; defaults to a reasonable server-side value.
	Limit ThreadListParamsLimit `json:"limit,omitempty"`

	// Optional provider filter; when set, only sessions recorded under these
	// providers are returned. When present but empty, includes all providers.
	ModelProviders *ThreadListParamsModelProviders `json:"modelProviders,omitempty"`

	// Optional sort key; defaults to created_at.
	SortKey interface{} `json:"sortKey,omitempty"`

	// Optional source filter; when set, only sessions from these source kinds are
	// returned. When omitted or empty, defaults to interactive sources.
	SourceKinds *ThreadListParamsSourceKinds `json:"sourceKinds,omitempty"`
}

// Optional archived filter; when set to true, only archived threads are returned.
// If false or null, only non-archived threads are returned.
type ThreadListParamsArchived *bool

// Opaque pagination cursor returned by a previous call.
type ThreadListParamsCursor *string

// Optional cwd filter; when set, only threads whose session cwd exactly matches
// this path are returned.
type ThreadListParamsCwd *string

// Optional page size; defaults to a reasonable server-side value.
type ThreadListParamsLimit *int

// Optional provider filter; when set, only sessions recorded under these providers
// are returned. When present but empty, includes all providers.
type ThreadListParamsModelProviders []string

// Optional source filter; when set, only sessions from these source kinds are
// returned. When omitted or empty, defaults to interactive sources.
type ThreadListParamsSourceKinds []ThreadSourceKind

type ThreadSortKey string

const ThreadSortKeyCreatedAt ThreadSortKey = "created_at"
const ThreadSortKeyUpdatedAt ThreadSortKey = "updated_at"

type ThreadSourceKind string

const ThreadSourceKindAppServer ThreadSourceKind = "appServer"
const ThreadSourceKindCli ThreadSourceKind = "cli"
const ThreadSourceKindExec ThreadSourceKind = "exec"
const ThreadSourceKindSubAgent ThreadSourceKind = "subAgent"
const ThreadSourceKindSubAgentCompact ThreadSourceKind = "subAgentCompact"
const ThreadSourceKindSubAgentOther ThreadSourceKind = "subAgentOther"
const ThreadSourceKindSubAgentThreadSpawn ThreadSourceKind = "subAgentThreadSpawn"
const ThreadSourceKindUnknown ThreadSourceKind = "unknown"

type ThreadListParamsSortKey_0 = ThreadSortKey

const ThreadSourceKindSubAgentReview ThreadSourceKind = "subAgentReview"
const ThreadSourceKindVscode ThreadSourceKind = "vscode"
