// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package dynamic_tool_call_params

type DynamicToolCallParams struct {
	// Arguments corresponds to the JSON schema field "arguments".
	Arguments interface{} `json:"arguments"`

	// CallId corresponds to the JSON schema field "callId".
	CallId string `json:"callId"`

	// ThreadId corresponds to the JSON schema field "threadId".
	ThreadId string `json:"threadId"`

	// Tool corresponds to the JSON schema field "tool".
	Tool string `json:"tool"`

	// TurnId corresponds to the JSON schema field "turnId".
	TurnId string `json:"turnId"`
}
