// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package thread_rollback_params

type ThreadRollbackParams struct {
	// The number of turns to drop from the end of the thread. Must be >= 1.
	//
	// This only modifies the thread's history and does not revert local file changes
	// that have been made by the agent. Clients are responsible for reverting these
	// changes.
	NumTurns int `json:"numTurns"`

	// ThreadId corresponds to the JSON schema field "threadId".
	ThreadId string `json:"threadId"`
}
