// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package event_msg

// A path that is guaranteed to be absolute and normalized (though it is not
// guaranteed to be canonicalized or exist on the filesystem).
//
// IMPORTANT: When deserializing an `AbsolutePathBuf`, a base path must be set
// using [AbsolutePathBufGuard::new]. If no base path is set, the deserialization
// will fail unless the path being deserialized is already absolute.
type AbsolutePathBuf string

type AgentMessageContent interface{}

// Agent lifecycle status, derived from emitted events.
type AgentStatus interface{}

// Determines the conditions under which the user is consulted to approve running
// the command proposed by Codex.
type AskForApproval interface{}

type ByteRange struct {
	// End byte offset (exclusive) within the UTF-8 text buffer.
	End int `json:"end"`

	// Start byte offset (inclusive) within the UTF-8 text buffer.
	Start int `json:"start"`
}

// The server's response to a tool call.
type CallToolResult struct {
	// Meta corresponds to the JSON schema field "_meta".
	Meta interface{} `json:"_meta,omitempty"`

	// Content corresponds to the JSON schema field "content".
	Content []interface{} `json:"content"`

	// IsError corresponds to the JSON schema field "isError".
	IsError CallToolResultIsError `json:"isError,omitempty"`

	// StructuredContent corresponds to the JSON schema field "structuredContent".
	StructuredContent interface{} `json:"structuredContent,omitempty"`
}

type CallToolResultIsError *bool

// Codex errors that we expose to clients.
type CodexErrorInfo interface{}

type ContentItem interface{}

type CreditsSnapshot struct {
	// Balance corresponds to the JSON schema field "balance".
	Balance CreditsSnapshotBalance `json:"balance,omitempty"`

	// HasCredits corresponds to the JSON schema field "has_credits".
	HasCredits bool `json:"has_credits"`

	// Unlimited corresponds to the JSON schema field "unlimited".
	Unlimited bool `json:"unlimited"`
}

type CreditsSnapshotBalance *string

type CustomPrompt struct {
	// ArgumentHint corresponds to the JSON schema field "argument_hint".
	ArgumentHint CustomPromptArgumentHint `json:"argument_hint,omitempty"`

	// Content corresponds to the JSON schema field "content".
	Content string `json:"content"`

	// Description corresponds to the JSON schema field "description".
	Description CustomPromptDescription `json:"description,omitempty"`

	// Name corresponds to the JSON schema field "name".
	Name string `json:"name"`

	// Path corresponds to the JSON schema field "path".
	Path string `json:"path"`
}

type CustomPromptArgumentHint *string

type CustomPromptDescription *string

type Duration struct {
	// Nanos corresponds to the JSON schema field "nanos".
	Nanos int `json:"nanos"`

	// Secs corresponds to the JSON schema field "secs".
	Secs int `json:"secs"`
}

// Response event from the agent NOTE: Make sure none of these values have optional
// types, as it will mess up the extension code-gen.
type EventMsg interface{}

type ExecCommandSource string

const ExecCommandSourceAgent ExecCommandSource = "agent"
const ExecCommandSourceUnifiedExecInteraction ExecCommandSource = "unified_exec_interaction"
const ExecCommandSourceUnifiedExecStartup ExecCommandSource = "unified_exec_startup"
const ExecCommandSourceUserShell ExecCommandSource = "user_shell"

type ExecCommandStatus string

const ExecCommandStatusCompleted ExecCommandStatus = "completed"
const ExecCommandStatusDeclined ExecCommandStatus = "declined"
const ExecCommandStatusFailed ExecCommandStatus = "failed"

type ExecOutputStream string

const ExecOutputStreamStderr ExecOutputStream = "stderr"
const ExecOutputStreamStdout ExecOutputStream = "stdout"

type FileChange interface{}

type FunctionCallOutputBody interface{}

// Responses API compatible content items that can be returned by a tool call. This
// is a subset of ContentItem with the types we support as function call outputs.
type FunctionCallOutputContentItem interface{}

// The payload we send back to OpenAI when reporting a tool call result.
//
// `body` serializes directly as the wire value for `function_call_output.output`.
// `success` remains internal metadata for downstream handling.
type FunctionCallOutputPayload struct {
	// Body corresponds to the JSON schema field "body".
	Body FunctionCallOutputBody `json:"body"`

	// Success corresponds to the JSON schema field "success".
	Success FunctionCallOutputPayloadSuccess `json:"success,omitempty"`
}

type FunctionCallOutputPayloadSuccess *bool

// Details of a ghost commit created from a repository state.
type GhostCommit struct {
	// Id corresponds to the JSON schema field "id".
	Id string `json:"id"`

	// Parent corresponds to the JSON schema field "parent".
	Parent GhostCommitParent `json:"parent,omitempty"`

	// PreexistingUntrackedDirs corresponds to the JSON schema field
	// "preexisting_untracked_dirs".
	PreexistingUntrackedDirs []string `json:"preexisting_untracked_dirs"`

	// PreexistingUntrackedFiles corresponds to the JSON schema field
	// "preexisting_untracked_files".
	PreexistingUntrackedFiles []string `json:"preexisting_untracked_files"`
}

type GhostCommitParent *string

type HistoryEntry struct {
	// ConversationId corresponds to the JSON schema field "conversation_id".
	ConversationId string `json:"conversation_id"`

	// Text corresponds to the JSON schema field "text".
	Text string `json:"text"`

	// Ts corresponds to the JSON schema field "ts".
	Ts int `json:"ts"`
}

type LocalShellAction interface{}

type LocalShellStatus string

const LocalShellStatusCompleted LocalShellStatus = "completed"
const LocalShellStatusInProgress LocalShellStatus = "in_progress"
const LocalShellStatusIncomplete LocalShellStatus = "incomplete"

type McpAuthStatus string

const McpAuthStatusBearerToken McpAuthStatus = "bearer_token"
const McpAuthStatusNotLoggedIn McpAuthStatus = "not_logged_in"
const McpAuthStatusOAuth McpAuthStatus = "o_auth"
const McpAuthStatusUnsupported McpAuthStatus = "unsupported"

type McpInvocation struct {
	// Arguments to the tool call.
	Arguments interface{} `json:"arguments,omitempty"`

	// Name of the MCP server as defined in the config.
	Server string `json:"server"`

	// Name of the tool as given by the MCP server.
	Tool string `json:"tool"`
}

type McpStartupFailure struct {
	// Error corresponds to the JSON schema field "error".
	Error string `json:"error"`

	// Server corresponds to the JSON schema field "server".
	Server string `json:"server"`
}

type McpStartupStatus interface{}

// Classifies an assistant message as interim commentary or final answer text.
//
// Providers do not emit this consistently, so callers must treat `None` as "phase
// unknown" and keep compatibility behavior for legacy models.
type MessagePhase interface{}

type ModeKind string

const ModeKindDefault ModeKind = "default"
const ModeKindPlan ModeKind = "plan"

type ModelRerouteReason string

const ModelRerouteReasonHighRiskCyberActivity ModelRerouteReason = "high_risk_cyber_activity"

type NetworkAccess string

const NetworkAccessEnabled NetworkAccess = "enabled"
const NetworkAccessRestricted NetworkAccess = "restricted"

type NetworkApprovalContext struct {
	// Host corresponds to the JSON schema field "host".
	Host string `json:"host"`

	// Protocol corresponds to the JSON schema field "protocol".
	Protocol NetworkApprovalProtocol `json:"protocol"`
}

type NetworkApprovalProtocol string

const NetworkApprovalProtocolHttp NetworkApprovalProtocol = "http"
const NetworkApprovalProtocolHttps NetworkApprovalProtocol = "https"
const NetworkApprovalProtocolSocks5Tcp NetworkApprovalProtocol = "socks5_tcp"
const NetworkApprovalProtocolSocks5Udp NetworkApprovalProtocol = "socks5_udp"

type ParsedCommand interface{}

type PatchApplyStatus string

const PatchApplyStatusCompleted PatchApplyStatus = "completed"
const PatchApplyStatusDeclined PatchApplyStatus = "declined"
const PatchApplyStatusFailed PatchApplyStatus = "failed"

type PlanItemArg struct {
	// Status corresponds to the JSON schema field "status".
	Status StepStatus `json:"status"`

	// Step corresponds to the JSON schema field "step".
	Step string `json:"step"`
}

type PlanType string

const PlanTypeBusiness PlanType = "business"
const PlanTypeEdu PlanType = "edu"
const PlanTypeEnterprise PlanType = "enterprise"
const PlanTypeFree PlanType = "free"
const PlanTypeGo PlanType = "go"
const PlanTypePlus PlanType = "plus"
const PlanTypePro PlanType = "pro"
const PlanTypeTeam PlanType = "team"
const PlanTypeUnknown PlanType = "unknown"

type RateLimitSnapshot struct {
	// Credits corresponds to the JSON schema field "credits".
	Credits *RateLimitSnapshotCredits `json:"credits,omitempty"`

	// LimitId corresponds to the JSON schema field "limit_id".
	LimitId RateLimitSnapshotLimitId `json:"limit_id,omitempty"`

	// LimitName corresponds to the JSON schema field "limit_name".
	LimitName RateLimitSnapshotLimitName `json:"limit_name,omitempty"`

	// PlanType corresponds to the JSON schema field "plan_type".
	PlanType interface{} `json:"plan_type,omitempty"`

	// Primary corresponds to the JSON schema field "primary".
	Primary *RateLimitSnapshotPrimary `json:"primary,omitempty"`

	// Secondary corresponds to the JSON schema field "secondary".
	Secondary *RateLimitSnapshotSecondary `json:"secondary,omitempty"`
}

type RateLimitSnapshotCredits struct {
	// Balance corresponds to the JSON schema field "balance".
	Balance CreditsSnapshotBalance `json:"balance,omitempty"`

	// HasCredits corresponds to the JSON schema field "has_credits".
	HasCredits bool `json:"has_credits"`

	// Unlimited corresponds to the JSON schema field "unlimited".
	Unlimited bool `json:"unlimited"`
}

type RateLimitSnapshotLimitId *string

type RateLimitSnapshotLimitName *string

type RateLimitSnapshotPrimary struct {
	// Unix timestamp (seconds since epoch) when the window resets.
	ResetsAt RateLimitWindowResetsAt `json:"resets_at,omitempty"`

	// Percentage (0-100) of the window that has been consumed.
	UsedPercent float64 `json:"used_percent"`

	// Rolling window duration, in minutes.
	WindowMinutes RateLimitWindowWindowMinutes `json:"window_minutes,omitempty"`
}

type RateLimitSnapshotSecondary struct {
	// Unix timestamp (seconds since epoch) when the window resets.
	ResetsAt RateLimitWindowResetsAt `json:"resets_at,omitempty"`

	// Percentage (0-100) of the window that has been consumed.
	UsedPercent float64 `json:"used_percent"`

	// Rolling window duration, in minutes.
	WindowMinutes RateLimitWindowWindowMinutes `json:"window_minutes,omitempty"`
}

type RateLimitWindow struct {
	// Unix timestamp (seconds since epoch) when the window resets.
	ResetsAt RateLimitWindowResetsAt `json:"resets_at,omitempty"`

	// Percentage (0-100) of the window that has been consumed.
	UsedPercent float64 `json:"used_percent"`

	// Rolling window duration, in minutes.
	WindowMinutes RateLimitWindowWindowMinutes `json:"window_minutes,omitempty"`
}

// Unix timestamp (seconds since epoch) when the window resets.
type RateLimitWindowResetsAt *int

// Rolling window duration, in minutes.
type RateLimitWindowWindowMinutes *int

// Determines how read-only file access is granted inside a restricted sandbox.
type ReadOnlyAccess interface{}

type ReasoningEffort string

const ReasoningEffortHigh ReasoningEffort = "high"
const ReasoningEffortLow ReasoningEffort = "low"
const ReasoningEffortMedium ReasoningEffort = "medium"
const ReasoningEffortMinimal ReasoningEffort = "minimal"
const ReasoningEffortNone ReasoningEffort = "none"
const ReasoningEffortXhigh ReasoningEffort = "xhigh"

type ReasoningItemContent interface{}

type ReasoningItemReasoningSummary interface{}

type RemoteSkillSummary struct {
	// Description corresponds to the JSON schema field "description".
	Description string `json:"description"`

	// Id corresponds to the JSON schema field "id".
	Id string `json:"id"`

	// Name corresponds to the JSON schema field "name".
	Name string `json:"name"`
}

// ID of a request, which can be either a string or an integer.
type RequestId interface{}

type RequestUserInputQuestion struct {
	// Header corresponds to the JSON schema field "header".
	Header string `json:"header"`

	// Id corresponds to the JSON schema field "id".
	Id string `json:"id"`

	// IsOther corresponds to the JSON schema field "isOther".
	IsOther bool `json:"isOther,omitempty"`

	// IsSecret corresponds to the JSON schema field "isSecret".
	IsSecret bool `json:"isSecret,omitempty"`

	// Options corresponds to the JSON schema field "options".
	Options *RequestUserInputQuestionOptions `json:"options,omitempty"`

	// Question corresponds to the JSON schema field "question".
	Question string `json:"question"`
}

type RequestUserInputQuestionOption struct {
	// Description corresponds to the JSON schema field "description".
	Description string `json:"description"`

	// Label corresponds to the JSON schema field "label".
	Label string `json:"label"`
}

type RequestUserInputQuestionOptions []RequestUserInputQuestionOption

// A known resource that the server is capable of reading.
type Resource struct {
	// Meta corresponds to the JSON schema field "_meta".
	Meta interface{} `json:"_meta,omitempty"`

	// Annotations corresponds to the JSON schema field "annotations".
	Annotations interface{} `json:"annotations,omitempty"`

	// Description corresponds to the JSON schema field "description".
	Description ResourceDescription `json:"description,omitempty"`

	// Icons corresponds to the JSON schema field "icons".
	Icons *ResourceIcons `json:"icons,omitempty"`

	// MimeType corresponds to the JSON schema field "mimeType".
	MimeType ResourceMimeType `json:"mimeType,omitempty"`

	// Name corresponds to the JSON schema field "name".
	Name string `json:"name"`

	// Size corresponds to the JSON schema field "size".
	Size ResourceSize `json:"size,omitempty"`

	// Title corresponds to the JSON schema field "title".
	Title ResourceTitle `json:"title,omitempty"`

	// Uri corresponds to the JSON schema field "uri".
	Uri string `json:"uri"`
}

type ResourceDescription *string

type ResourceIcons []interface{}

type ResourceMimeType *string

type ResourceSize *int

// A template description for resources available on the server.
type ResourceTemplate struct {
	// Annotations corresponds to the JSON schema field "annotations".
	Annotations interface{} `json:"annotations,omitempty"`

	// Description corresponds to the JSON schema field "description".
	Description ResourceTemplateDescription `json:"description,omitempty"`

	// MimeType corresponds to the JSON schema field "mimeType".
	MimeType ResourceTemplateMimeType `json:"mimeType,omitempty"`

	// Name corresponds to the JSON schema field "name".
	Name string `json:"name"`

	// Title corresponds to the JSON schema field "title".
	Title ResourceTemplateTitle `json:"title,omitempty"`

	// UriTemplate corresponds to the JSON schema field "uriTemplate".
	UriTemplate string `json:"uriTemplate"`
}

type ResourceTemplateDescription *string

type ResourceTemplateMimeType *string

type ResourceTemplateTitle *string

type ResourceTitle *string

type ResponseItem interface{}

type ResultOfCallToolResultOrString interface{}

// Location of the code related to a review finding.
type ReviewCodeLocation struct {
	// AbsoluteFilePath corresponds to the JSON schema field "absolute_file_path".
	AbsoluteFilePath string `json:"absolute_file_path"`

	// LineRange corresponds to the JSON schema field "line_range".
	LineRange ReviewLineRange `json:"line_range"`
}

// A single review finding describing an observed issue or recommendation.
type ReviewFinding struct {
	// Body corresponds to the JSON schema field "body".
	Body string `json:"body"`

	// CodeLocation corresponds to the JSON schema field "code_location".
	CodeLocation ReviewCodeLocation `json:"code_location"`

	// ConfidenceScore corresponds to the JSON schema field "confidence_score".
	ConfidenceScore float64 `json:"confidence_score"`

	// Priority corresponds to the JSON schema field "priority".
	Priority int `json:"priority"`

	// Title corresponds to the JSON schema field "title".
	Title string `json:"title"`
}

// Inclusive line range in a file associated with the finding.
type ReviewLineRange struct {
	// End corresponds to the JSON schema field "end".
	End int `json:"end"`

	// Start corresponds to the JSON schema field "start".
	Start int `json:"start"`
}

// Structured review result produced by a child review session.
type ReviewOutputEvent struct {
	// Findings corresponds to the JSON schema field "findings".
	Findings []ReviewFinding `json:"findings"`

	// OverallConfidenceScore corresponds to the JSON schema field
	// "overall_confidence_score".
	OverallConfidenceScore float64 `json:"overall_confidence_score"`

	// OverallCorrectness corresponds to the JSON schema field "overall_correctness".
	OverallCorrectness string `json:"overall_correctness"`

	// OverallExplanation corresponds to the JSON schema field "overall_explanation".
	OverallExplanation string `json:"overall_explanation"`
}

type ReviewTarget interface{}

// Determines execution restrictions for model shell commands.
type SandboxPolicy interface{}

type SessionNetworkProxyRuntime struct {
	// AdminAddr corresponds to the JSON schema field "admin_addr".
	AdminAddr string `json:"admin_addr"`

	// HttpAddr corresponds to the JSON schema field "http_addr".
	HttpAddr string `json:"http_addr"`

	// SocksAddr corresponds to the JSON schema field "socks_addr".
	SocksAddr string `json:"socks_addr"`
}

type SkillDependencies struct {
	// Tools corresponds to the JSON schema field "tools".
	Tools []SkillToolDependency `json:"tools"`
}

type SkillErrorInfo struct {
	// Message corresponds to the JSON schema field "message".
	Message string `json:"message"`

	// Path corresponds to the JSON schema field "path".
	Path string `json:"path"`
}

type SkillInterface struct {
	// BrandColor corresponds to the JSON schema field "brand_color".
	BrandColor SkillInterfaceBrandColor `json:"brand_color,omitempty"`

	// DefaultPrompt corresponds to the JSON schema field "default_prompt".
	DefaultPrompt SkillInterfaceDefaultPrompt `json:"default_prompt,omitempty"`

	// DisplayName corresponds to the JSON schema field "display_name".
	DisplayName SkillInterfaceDisplayName `json:"display_name,omitempty"`

	// IconLarge corresponds to the JSON schema field "icon_large".
	IconLarge SkillInterfaceIconLarge `json:"icon_large,omitempty"`

	// IconSmall corresponds to the JSON schema field "icon_small".
	IconSmall SkillInterfaceIconSmall `json:"icon_small,omitempty"`

	// ShortDescription corresponds to the JSON schema field "short_description".
	ShortDescription SkillInterfaceShortDescription `json:"short_description,omitempty"`
}

type SkillInterfaceBrandColor *string

type SkillInterfaceDefaultPrompt *string

type SkillInterfaceDisplayName *string

type SkillInterfaceIconLarge *string

type SkillInterfaceIconSmall *string

type SkillInterfaceShortDescription *string

type SkillMetadata struct {
	// Dependencies corresponds to the JSON schema field "dependencies".
	Dependencies *SkillMetadataDependencies `json:"dependencies,omitempty"`

	// Description corresponds to the JSON schema field "description".
	Description string `json:"description"`

	// Enabled corresponds to the JSON schema field "enabled".
	Enabled bool `json:"enabled"`

	// Interface corresponds to the JSON schema field "interface".
	Interface *SkillMetadataInterface `json:"interface,omitempty"`

	// Name corresponds to the JSON schema field "name".
	Name string `json:"name"`

	// Path corresponds to the JSON schema field "path".
	Path string `json:"path"`

	// Scope corresponds to the JSON schema field "scope".
	Scope SkillScope `json:"scope"`

	// Legacy short_description from SKILL.md. Prefer SKILL.json
	// interface.short_description.
	ShortDescription SkillMetadataShortDescription `json:"short_description,omitempty"`
}

type SkillMetadataDependencies struct {
	// Tools corresponds to the JSON schema field "tools".
	Tools []SkillToolDependency `json:"tools"`
}

type SkillMetadataInterface struct {
	// BrandColor corresponds to the JSON schema field "brand_color".
	BrandColor SkillInterfaceBrandColor `json:"brand_color,omitempty"`

	// DefaultPrompt corresponds to the JSON schema field "default_prompt".
	DefaultPrompt SkillInterfaceDefaultPrompt `json:"default_prompt,omitempty"`

	// DisplayName corresponds to the JSON schema field "display_name".
	DisplayName SkillInterfaceDisplayName `json:"display_name,omitempty"`

	// IconLarge corresponds to the JSON schema field "icon_large".
	IconLarge SkillInterfaceIconLarge `json:"icon_large,omitempty"`

	// IconSmall corresponds to the JSON schema field "icon_small".
	IconSmall SkillInterfaceIconSmall `json:"icon_small,omitempty"`

	// ShortDescription corresponds to the JSON schema field "short_description".
	ShortDescription SkillInterfaceShortDescription `json:"short_description,omitempty"`
}

// Legacy short_description from SKILL.md. Prefer SKILL.json
// interface.short_description.
type SkillMetadataShortDescription *string

type SkillScope string

const SkillScopeAdmin SkillScope = "admin"
const SkillScopeRepo SkillScope = "repo"
const SkillScopeSystem SkillScope = "system"
const SkillScopeUser SkillScope = "user"

type SkillToolDependency struct {
	// Command corresponds to the JSON schema field "command".
	Command SkillToolDependencyCommand `json:"command,omitempty"`

	// Description corresponds to the JSON schema field "description".
	Description SkillToolDependencyDescription `json:"description,omitempty"`

	// Transport corresponds to the JSON schema field "transport".
	Transport SkillToolDependencyTransport `json:"transport,omitempty"`

	// Type corresponds to the JSON schema field "type".
	Type string `json:"type"`

	// Url corresponds to the JSON schema field "url".
	Url SkillToolDependencyUrl `json:"url,omitempty"`

	// Value corresponds to the JSON schema field "value".
	Value string `json:"value"`
}

type SkillToolDependencyCommand *string

type SkillToolDependencyDescription *string

type SkillToolDependencyTransport *string

type SkillToolDependencyUrl *string

type SkillsListEntry struct {
	// Cwd corresponds to the JSON schema field "cwd".
	Cwd string `json:"cwd"`

	// Errors corresponds to the JSON schema field "errors".
	Errors []SkillErrorInfo `json:"errors"`

	// Skills corresponds to the JSON schema field "skills".
	Skills []SkillMetadata `json:"skills"`
}

type StepStatus string

const StepStatusCompleted StepStatus = "completed"
const StepStatusInProgress StepStatus = "in_progress"
const StepStatusPending StepStatus = "pending"

type TextElement struct {
	// Byte range in the parent `text` buffer that this element occupies.
	ByteRange TextElementByteRange `json:"byte_range"`

	// Optional human-readable placeholder for the element, displayed in the UI.
	Placeholder TextElementPlaceholder `json:"placeholder,omitempty"`
}

// Byte range in the parent `text` buffer that this element occupies.
type TextElementByteRange struct {
	// End byte offset (exclusive) within the UTF-8 text buffer.
	End int `json:"end"`

	// Start byte offset (inclusive) within the UTF-8 text buffer.
	Start int `json:"start"`
}

// Optional human-readable placeholder for the element, displayed in the UI.
type TextElementPlaceholder *string

type ThreadId string

type TokenUsage struct {
	// CachedInputTokens corresponds to the JSON schema field "cached_input_tokens".
	CachedInputTokens int `json:"cached_input_tokens"`

	// InputTokens corresponds to the JSON schema field "input_tokens".
	InputTokens int `json:"input_tokens"`

	// OutputTokens corresponds to the JSON schema field "output_tokens".
	OutputTokens int `json:"output_tokens"`

	// ReasoningOutputTokens corresponds to the JSON schema field
	// "reasoning_output_tokens".
	ReasoningOutputTokens int `json:"reasoning_output_tokens"`

	// TotalTokens corresponds to the JSON schema field "total_tokens".
	TotalTokens int `json:"total_tokens"`
}

type TokenUsageInfo struct {
	// LastTokenUsage corresponds to the JSON schema field "last_token_usage".
	LastTokenUsage TokenUsage `json:"last_token_usage"`

	// ModelContextWindow corresponds to the JSON schema field "model_context_window".
	ModelContextWindow TokenUsageInfoModelContextWindow `json:"model_context_window,omitempty"`

	// TotalTokenUsage corresponds to the JSON schema field "total_token_usage".
	TotalTokenUsage TokenUsage `json:"total_token_usage"`
}

type TokenUsageInfoModelContextWindow *int

// Definition for a tool the client can call.
type Tool struct {
	// Meta corresponds to the JSON schema field "_meta".
	Meta interface{} `json:"_meta,omitempty"`

	// Annotations corresponds to the JSON schema field "annotations".
	Annotations interface{} `json:"annotations,omitempty"`

	// Description corresponds to the JSON schema field "description".
	Description ToolDescription `json:"description,omitempty"`

	// Icons corresponds to the JSON schema field "icons".
	Icons *ToolIcons `json:"icons,omitempty"`

	// InputSchema corresponds to the JSON schema field "inputSchema".
	InputSchema interface{} `json:"inputSchema"`

	// Name corresponds to the JSON schema field "name".
	Name string `json:"name"`

	// OutputSchema corresponds to the JSON schema field "outputSchema".
	OutputSchema interface{} `json:"outputSchema,omitempty"`

	// Title corresponds to the JSON schema field "title".
	Title ToolTitle `json:"title,omitempty"`
}

type ToolDescription *string

type ToolIcons []interface{}

type ToolTitle *string

type TurnAbortReason string

type RateLimitSnapshotPlanType_0 = PlanType

type RateLimitSnapshotPrimary_0 = RateLimitWindow

type SkillMetadataInterface_0 = SkillInterface

type SkillMetadataDependencies_0 = SkillDependencies

type RateLimitSnapshotSecondary_0 = RateLimitWindow

type RateLimitSnapshotCredits_0 = CreditsSnapshot

const TurnAbortReasonInterrupted TurnAbortReason = "interrupted"
const TurnAbortReasonReplaced TurnAbortReason = "replaced"
const TurnAbortReasonReviewEnded TurnAbortReason = "review_ended"

type TurnItem interface{}

// User input
type UserInput interface{}

type WebSearchAction interface{}
