// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package mcp_tool_call_progress_notification

type McpToolCallProgressNotification struct {
	// ItemId corresponds to the JSON schema field "itemId".
	ItemId string `json:"itemId"`

	// Message corresponds to the JSON schema field "message".
	Message string `json:"message"`

	// ThreadId corresponds to the JSON schema field "threadId".
	ThreadId string `json:"threadId"`

	// TurnId corresponds to the JSON schema field "turnId".
	TurnId string `json:"turnId"`
}
