// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package turn_plan_updated_notification

type TurnPlanStep struct {
	// Status corresponds to the JSON schema field "status".
	Status TurnPlanStepStatus `json:"status"`

	// Step corresponds to the JSON schema field "step".
	Step string `json:"step"`
}

type TurnPlanStepStatus string

const TurnPlanStepStatusCompleted TurnPlanStepStatus = "completed"
const TurnPlanStepStatusInProgress TurnPlanStepStatus = "inProgress"
const TurnPlanStepStatusPending TurnPlanStepStatus = "pending"

type TurnPlanUpdatedNotification struct {
	// Explanation corresponds to the JSON schema field "explanation".
	Explanation TurnPlanUpdatedNotificationExplanation `json:"explanation,omitempty"`

	// Plan corresponds to the JSON schema field "plan".
	Plan []TurnPlanStep `json:"plan"`

	// ThreadId corresponds to the JSON schema field "threadId".
	ThreadId string `json:"threadId"`

	// TurnId corresponds to the JSON schema field "turnId".
	TurnId string `json:"turnId"`
}

type TurnPlanUpdatedNotificationExplanation *string
