// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package file_change_request_approval_params

type FileChangeRequestApprovalParams struct {
	// [UNSTABLE] When set, the agent is asking the user to allow writes under this
	// root for the remainder of the session (unclear if this is honored today).
	GrantRoot FileChangeRequestApprovalParamsGrantRoot `json:"grantRoot,omitempty"`

	// ItemId corresponds to the JSON schema field "itemId".
	ItemId string `json:"itemId"`

	// Optional explanatory reason (e.g. request for extra write access).
	Reason FileChangeRequestApprovalParamsReason `json:"reason,omitempty"`

	// ThreadId corresponds to the JSON schema field "threadId".
	ThreadId string `json:"threadId"`

	// TurnId corresponds to the JSON schema field "turnId".
	TurnId string `json:"turnId"`
}

// [UNSTABLE] When set, the agent is asking the user to allow writes under this
// root for the remainder of the session (unclear if this is honored today).
type FileChangeRequestApprovalParamsGrantRoot *string

// Optional explanatory reason (e.g. request for extra write access).
type FileChangeRequestApprovalParamsReason *string
