// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package fuzzy_file_search_session_completed_notification

type FuzzyFileSearchSessionCompletedNotification struct {
	// SessionId corresponds to the JSON schema field "sessionId".
	SessionId string `json:"sessionId"`
}
