// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package account_updated_notification

type AccountUpdatedNotification struct {
	// AuthMode corresponds to the JSON schema field "authMode".
	AuthMode interface{} `json:"authMode,omitempty"`
}

// Authentication mode for OpenAI-backed providers.
type AuthMode interface{}
