// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package cancel_login_account_response

type CancelLoginAccountResponse struct {
	// Status corresponds to the JSON schema field "status".
	Status CancelLoginAccountStatus `json:"status"`
}

type CancelLoginAccountStatus string

const CancelLoginAccountStatusCanceled CancelLoginAccountStatus = "canceled"
const CancelLoginAccountStatusNotFound CancelLoginAccountStatus = "notFound"
