// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package skills_remote_read_response

type RemoteSkillSummary struct {
	// Description corresponds to the JSON schema field "description".
	Description string `json:"description"`

	// Id corresponds to the JSON schema field "id".
	Id string `json:"id"`

	// Name corresponds to the JSON schema field "name".
	Name string `json:"name"`
}

type SkillsRemoteReadResponse struct {
	// Data corresponds to the JSON schema field "data".
	Data []RemoteSkillSummary `json:"data"`
}
