// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package plan_delta_notification

// EXPERIMENTAL - proposed plan streaming deltas for plan items. Clients should not
// assume concatenated deltas match the completed plan item content.
type PlanDeltaNotification struct {
	// Delta corresponds to the JSON schema field "delta".
	Delta string `json:"delta"`

	// ItemId corresponds to the JSON schema field "itemId".
	ItemId string `json:"itemId"`

	// ThreadId corresponds to the JSON schema field "threadId".
	ThreadId string `json:"threadId"`

	// TurnId corresponds to the JSON schema field "turnId".
	TurnId string `json:"turnId"`
}
