// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package command_execution_request_approval_params

type CommandAction interface{}

type CommandExecutionRequestApprovalParams struct {
	// Unique identifier for this specific approval callback.
	//
	// For regular shell/unified_exec approvals, this is null.
	//
	// For zsh-exec-bridge subcommand approvals, multiple callbacks can belong to one
	// parent `itemId`, so `approvalId` is a distinct opaque callback id (a UUID) used
	// to disambiguate routing.
	ApprovalId CommandExecutionRequestApprovalParamsApprovalId `json:"approvalId,omitempty"`

	// The command to be executed.
	Command CommandExecutionRequestApprovalParamsCommand `json:"command,omitempty"`

	// Best-effort parsed command actions for friendly display.
	CommandActions *CommandExecutionRequestApprovalParamsCommandActions `json:"commandActions,omitempty"`

	// The command's working directory.
	Cwd CommandExecutionRequestApprovalParamsCwd `json:"cwd,omitempty"`

	// ItemId corresponds to the JSON schema field "itemId".
	ItemId string `json:"itemId"`

	// Optional proposed execpolicy amendment to allow similar commands without
	// prompting.
	ProposedExecpolicyAmendment *CommandExecutionRequestApprovalParamsProposedExecpolicyAmendment `json:"proposedExecpolicyAmendment,omitempty"`

	// Optional explanatory reason (e.g. request for network access).
	Reason CommandExecutionRequestApprovalParamsReason `json:"reason,omitempty"`

	// ThreadId corresponds to the JSON schema field "threadId".
	ThreadId string `json:"threadId"`

	// TurnId corresponds to the JSON schema field "turnId".
	TurnId string `json:"turnId"`
}

// Unique identifier for this specific approval callback.
//
// For regular shell/unified_exec approvals, this is null.
//
// For zsh-exec-bridge subcommand approvals, multiple callbacks can belong to one
// parent `itemId`, so `approvalId` is a distinct opaque callback id (a UUID) used
// to disambiguate routing.
type CommandExecutionRequestApprovalParamsApprovalId *string

// The command to be executed.
type CommandExecutionRequestApprovalParamsCommand *string

// Best-effort parsed command actions for friendly display.
type CommandExecutionRequestApprovalParamsCommandActions []CommandAction

// The command's working directory.
type CommandExecutionRequestApprovalParamsCwd *string

// Optional proposed execpolicy amendment to allow similar commands without
// prompting.
type CommandExecutionRequestApprovalParamsProposedExecpolicyAmendment []string

// Optional explanatory reason (e.g. request for network access).
type CommandExecutionRequestApprovalParamsReason *string
