// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package thread_compact_start_params

type ThreadCompactStartParams struct {
	// ThreadId corresponds to the JSON schema field "threadId".
	ThreadId string `json:"threadId"`
}
