// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package terminal_interaction_notification

type TerminalInteractionNotification struct {
	// ItemId corresponds to the JSON schema field "itemId".
	ItemId string `json:"itemId"`

	// ProcessId corresponds to the JSON schema field "processId".
	ProcessId string `json:"processId"`

	// Stdin corresponds to the JSON schema field "stdin".
	Stdin string `json:"stdin"`

	// ThreadId corresponds to the JSON schema field "threadId".
	ThreadId string `json:"threadId"`

	// TurnId corresponds to the JSON schema field "turnId".
	TurnId string `json:"turnId"`
}
