// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package skills_list_response

type SkillDependencies struct {
	// Tools corresponds to the JSON schema field "tools".
	Tools []SkillToolDependency `json:"tools"`
}

type SkillErrorInfo struct {
	// Message corresponds to the JSON schema field "message".
	Message string `json:"message"`

	// Path corresponds to the JSON schema field "path".
	Path string `json:"path"`
}

type SkillInterface struct {
	// BrandColor corresponds to the JSON schema field "brandColor".
	BrandColor SkillInterfaceBrandColor `json:"brandColor,omitempty"`

	// DefaultPrompt corresponds to the JSON schema field "defaultPrompt".
	DefaultPrompt SkillInterfaceDefaultPrompt `json:"defaultPrompt,omitempty"`

	// DisplayName corresponds to the JSON schema field "displayName".
	DisplayName SkillInterfaceDisplayName `json:"displayName,omitempty"`

	// IconLarge corresponds to the JSON schema field "iconLarge".
	IconLarge SkillInterfaceIconLarge `json:"iconLarge,omitempty"`

	// IconSmall corresponds to the JSON schema field "iconSmall".
	IconSmall SkillInterfaceIconSmall `json:"iconSmall,omitempty"`

	// ShortDescription corresponds to the JSON schema field "shortDescription".
	ShortDescription SkillInterfaceShortDescription `json:"shortDescription,omitempty"`
}

type SkillInterfaceBrandColor *string

type SkillInterfaceDefaultPrompt *string

type SkillInterfaceDisplayName *string

type SkillInterfaceIconLarge *string

type SkillInterfaceIconSmall *string

type SkillInterfaceShortDescription *string

type SkillMetadata struct {
	// Dependencies corresponds to the JSON schema field "dependencies".
	Dependencies *SkillMetadataDependencies `json:"dependencies,omitempty"`

	// Description corresponds to the JSON schema field "description".
	Description string `json:"description"`

	// Enabled corresponds to the JSON schema field "enabled".
	Enabled bool `json:"enabled"`

	// Interface corresponds to the JSON schema field "interface".
	Interface *SkillMetadataInterface `json:"interface,omitempty"`

	// Name corresponds to the JSON schema field "name".
	Name string `json:"name"`

	// Path corresponds to the JSON schema field "path".
	Path string `json:"path"`

	// Scope corresponds to the JSON schema field "scope".
	Scope SkillScope `json:"scope"`

	// Legacy short_description from SKILL.md. Prefer SKILL.json
	// interface.short_description.
	ShortDescription SkillMetadataShortDescription `json:"shortDescription,omitempty"`
}

type SkillMetadataDependencies struct {
	// Tools corresponds to the JSON schema field "tools".
	Tools []SkillToolDependency `json:"tools"`
}

type SkillMetadataInterface struct {
	// BrandColor corresponds to the JSON schema field "brandColor".
	BrandColor SkillInterfaceBrandColor `json:"brandColor,omitempty"`

	// DefaultPrompt corresponds to the JSON schema field "defaultPrompt".
	DefaultPrompt SkillInterfaceDefaultPrompt `json:"defaultPrompt,omitempty"`

	// DisplayName corresponds to the JSON schema field "displayName".
	DisplayName SkillInterfaceDisplayName `json:"displayName,omitempty"`

	// IconLarge corresponds to the JSON schema field "iconLarge".
	IconLarge SkillInterfaceIconLarge `json:"iconLarge,omitempty"`

	// IconSmall corresponds to the JSON schema field "iconSmall".
	IconSmall SkillInterfaceIconSmall `json:"iconSmall,omitempty"`

	// ShortDescription corresponds to the JSON schema field "shortDescription".
	ShortDescription SkillInterfaceShortDescription `json:"shortDescription,omitempty"`
}

// Legacy short_description from SKILL.md. Prefer SKILL.json
// interface.short_description.
type SkillMetadataShortDescription *string

type SkillScope string

const SkillScopeAdmin SkillScope = "admin"
const SkillScopeRepo SkillScope = "repo"
const SkillScopeSystem SkillScope = "system"

type SkillMetadataInterface_0 = SkillInterface

type SkillMetadataDependencies_0 = SkillDependencies

const SkillScopeUser SkillScope = "user"

type SkillToolDependency struct {
	// Command corresponds to the JSON schema field "command".
	Command SkillToolDependencyCommand `json:"command,omitempty"`

	// Description corresponds to the JSON schema field "description".
	Description SkillToolDependencyDescription `json:"description,omitempty"`

	// Transport corresponds to the JSON schema field "transport".
	Transport SkillToolDependencyTransport `json:"transport,omitempty"`

	// Type corresponds to the JSON schema field "type".
	Type string `json:"type"`

	// Url corresponds to the JSON schema field "url".
	Url SkillToolDependencyUrl `json:"url,omitempty"`

	// Value corresponds to the JSON schema field "value".
	Value string `json:"value"`
}

type SkillToolDependencyCommand *string

type SkillToolDependencyDescription *string

type SkillToolDependencyTransport *string

type SkillToolDependencyUrl *string

type SkillsListEntry struct {
	// Cwd corresponds to the JSON schema field "cwd".
	Cwd string `json:"cwd"`

	// Errors corresponds to the JSON schema field "errors".
	Errors []SkillErrorInfo `json:"errors"`

	// Skills corresponds to the JSON schema field "skills".
	Skills []SkillMetadata `json:"skills"`
}

type SkillsListResponse struct {
	// Data corresponds to the JSON schema field "data".
	Data []SkillsListEntry `json:"data"`
}
