// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package config_warning_notification

// Optional extra guidance or error details.
type ConfigWarningNotificationDetails *string

// Optional path to the config file that triggered the warning.
type ConfigWarningNotificationPath *string

type TextPosition struct {
	// 1-based column number (in Unicode scalar values).
	Column int `json:"column"`

	// 1-based line number.
	Line int `json:"line"`
}

type TextRange struct {
	// End corresponds to the JSON schema field "end".
	End TextPosition `json:"end"`

	// Start corresponds to the JSON schema field "start".
	Start TextPosition `json:"start"`
}

type ConfigWarningNotificationRange_0 = TextRange

type ConfigWarningNotification struct {
	// Optional extra guidance or error details.
	Details ConfigWarningNotificationDetails `json:"details,omitempty"`

	// Optional path to the config file that triggered the warning.
	Path ConfigWarningNotificationPath `json:"path,omitempty"`

	// Optional range for the error location inside the config file.
	Range *ConfigWarningNotificationRange `json:"range,omitempty"`

	// Concise summary of the warning.
	Summary string `json:"summary"`
}

// Optional range for the error location inside the config file.
type ConfigWarningNotificationRange struct {
	// End corresponds to the JSON schema field "end".
	End TextPosition `json:"end"`

	// Start corresponds to the JSON schema field "start".
	Start TextPosition `json:"start"`
}
