// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package feedback_upload_response

type FeedbackUploadResponse struct {
	// ThreadId corresponds to the JSON schema field "threadId".
	ThreadId string `json:"threadId"`
}
