// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package config_read_params

type ConfigReadParams struct {
	// Optional working directory to resolve project config layers. If specified,
	// return the effective config as seen from that directory (i.e., including any
	// project layers between `cwd` and the project/repo root).
	Cwd ConfigReadParamsCwd `json:"cwd,omitempty"`

	// IncludeLayers corresponds to the JSON schema field "includeLayers".
	IncludeLayers bool `json:"includeLayers,omitempty"`
}

// Optional working directory to resolve project config layers. If specified,
// return the effective config as seen from that directory (i.e., including any
// project layers between `cwd` and the project/repo root).
type ConfigReadParamsCwd *string
