// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package thread_set_name_params

type ThreadSetNameParams struct {
	// Name corresponds to the JSON schema field "name".
	Name string `json:"name"`

	// ThreadId corresponds to the JSON schema field "threadId".
	ThreadId string `json:"threadId"`
}
