// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package reasoning_summary_text_delta_notification

type ReasoningSummaryTextDeltaNotification struct {
	// Delta corresponds to the JSON schema field "delta".
	Delta string `json:"delta"`

	// ItemId corresponds to the JSON schema field "itemId".
	ItemId string `json:"itemId"`

	// SummaryIndex corresponds to the JSON schema field "summaryIndex".
	SummaryIndex int `json:"summaryIndex"`

	// ThreadId corresponds to the JSON schema field "threadId".
	ThreadId string `json:"threadId"`

	// TurnId corresponds to the JSON schema field "turnId".
	TurnId string `json:"turnId"`
}
