// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package list_mcp_server_status_response

type ListMcpServerStatusResponse struct {
	// Data corresponds to the JSON schema field "data".
	Data []McpServerStatus `json:"data"`

	// Opaque cursor to pass to the next call to continue after the last item. If
	// None, there are no more items to return.
	NextCursor ListMcpServerStatusResponseNextCursor `json:"nextCursor,omitempty"`
}

// Opaque cursor to pass to the next call to continue after the last item. If None,
// there are no more items to return.
type ListMcpServerStatusResponseNextCursor *string

type McpAuthStatus string

const McpAuthStatusBearerToken McpAuthStatus = "bearerToken"
const McpAuthStatusNotLoggedIn McpAuthStatus = "notLoggedIn"
const McpAuthStatusOAuth McpAuthStatus = "oAuth"
const McpAuthStatusUnsupported McpAuthStatus = "unsupported"

type McpServerStatus struct {
	// AuthStatus corresponds to the JSON schema field "authStatus".
	AuthStatus McpAuthStatus `json:"authStatus"`

	// Name corresponds to the JSON schema field "name".
	Name string `json:"name"`

	// ResourceTemplates corresponds to the JSON schema field "resourceTemplates".
	ResourceTemplates []ResourceTemplate `json:"resourceTemplates"`

	// Resources corresponds to the JSON schema field "resources".
	Resources []Resource `json:"resources"`

	// Tools corresponds to the JSON schema field "tools".
	Tools McpServerStatusTools `json:"tools"`
}

type McpServerStatusTools map[string]Tool

// A known resource that the server is capable of reading.
type Resource struct {
	// Meta corresponds to the JSON schema field "_meta".
	Meta interface{} `json:"_meta,omitempty"`

	// Annotations corresponds to the JSON schema field "annotations".
	Annotations interface{} `json:"annotations,omitempty"`

	// Description corresponds to the JSON schema field "description".
	Description ResourceDescription `json:"description,omitempty"`

	// Icons corresponds to the JSON schema field "icons".
	Icons *ResourceIcons `json:"icons,omitempty"`

	// MimeType corresponds to the JSON schema field "mimeType".
	MimeType ResourceMimeType `json:"mimeType,omitempty"`

	// Name corresponds to the JSON schema field "name".
	Name string `json:"name"`

	// Size corresponds to the JSON schema field "size".
	Size ResourceSize `json:"size,omitempty"`

	// Title corresponds to the JSON schema field "title".
	Title ResourceTitle `json:"title,omitempty"`

	// Uri corresponds to the JSON schema field "uri".
	Uri string `json:"uri"`
}

type ResourceDescription *string

type ResourceIcons []interface{}

type ResourceMimeType *string

type ResourceSize *int

// A template description for resources available on the server.
type ResourceTemplate struct {
	// Annotations corresponds to the JSON schema field "annotations".
	Annotations interface{} `json:"annotations,omitempty"`

	// Description corresponds to the JSON schema field "description".
	Description ResourceTemplateDescription `json:"description,omitempty"`

	// MimeType corresponds to the JSON schema field "mimeType".
	MimeType ResourceTemplateMimeType `json:"mimeType,omitempty"`

	// Name corresponds to the JSON schema field "name".
	Name string `json:"name"`

	// Title corresponds to the JSON schema field "title".
	Title ResourceTemplateTitle `json:"title,omitempty"`

	// UriTemplate corresponds to the JSON schema field "uriTemplate".
	UriTemplate string `json:"uriTemplate"`
}

type ResourceTemplateDescription *string

type ResourceTemplateMimeType *string

type ResourceTemplateTitle *string

type ResourceTitle *string

// Definition for a tool the client can call.
type Tool struct {
	// Meta corresponds to the JSON schema field "_meta".
	Meta interface{} `json:"_meta,omitempty"`

	// Annotations corresponds to the JSON schema field "annotations".
	Annotations interface{} `json:"annotations,omitempty"`

	// Description corresponds to the JSON schema field "description".
	Description ToolDescription `json:"description,omitempty"`

	// Icons corresponds to the JSON schema field "icons".
	Icons *ToolIcons `json:"icons,omitempty"`

	// InputSchema corresponds to the JSON schema field "inputSchema".
	InputSchema interface{} `json:"inputSchema"`

	// Name corresponds to the JSON schema field "name".
	Name string `json:"name"`

	// OutputSchema corresponds to the JSON schema field "outputSchema".
	OutputSchema interface{} `json:"outputSchema,omitempty"`

	// Title corresponds to the JSON schema field "title".
	Title ToolTitle `json:"title,omitempty"`
}

type ToolDescription *string

type ToolIcons []interface{}

type ToolTitle *string
