// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package apps_list_params

// EXPERIMENTAL - list available apps/connectors.
type AppsListParams struct {
	// Opaque pagination cursor returned by a previous call.
	Cursor AppsListParamsCursor `json:"cursor,omitempty"`

	// When true, bypass app caches and fetch the latest data from sources.
	ForceRefetch *bool `json:"forceRefetch,omitempty"`

	// Optional page size; defaults to a reasonable server-side value.
	Limit AppsListParamsLimit `json:"limit,omitempty"`

	// Optional thread id used to evaluate app feature gating from that thread's
	// config.
	ThreadId AppsListParamsThreadId `json:"threadId,omitempty"`
}

// Opaque pagination cursor returned by a previous call.
type AppsListParamsCursor *string

// Optional page size; defaults to a reasonable server-side value.
type AppsListParamsLimit *int

// Optional thread id used to evaluate app feature gating from that thread's
// config.
type AppsListParamsThreadId *string
