// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package windows_world_writable_warning_notification

type WindowsWorldWritableWarningNotification struct {
	// ExtraCount corresponds to the JSON schema field "extraCount".
	ExtraCount int `json:"extraCount"`

	// FailedScan corresponds to the JSON schema field "failedScan".
	FailedScan bool `json:"failedScan"`

	// SamplePaths corresponds to the JSON schema field "samplePaths".
	SamplePaths []string `json:"samplePaths"`
}
