// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package thread_name_updated_notification

type ThreadNameUpdatedNotification struct {
	// ThreadId corresponds to the JSON schema field "threadId".
	ThreadId string `json:"threadId"`

	// ThreadName corresponds to the JSON schema field "threadName".
	ThreadName ThreadNameUpdatedNotificationThreadName `json:"threadName,omitempty"`
}

type ThreadNameUpdatedNotificationThreadName *string
