// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package cancel_login_account_params

type CancelLoginAccountParams struct {
	// LoginId corresponds to the JSON schema field "loginId".
	LoginId string `json:"loginId"`
}
