// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package account_rate_limits_updated_notification

type RateLimitSnapshotCredits_0 = CreditsSnapshot

type RateLimitSnapshotSecondary_0 = RateLimitWindow

type PlanType string

const PlanTypeFree PlanType = "free"
const PlanTypeGo PlanType = "go"
const PlanTypePlus PlanType = "plus"
const PlanTypePro PlanType = "pro"
const PlanTypeTeam PlanType = "team"
const PlanTypeBusiness PlanType = "business"
const PlanTypeEnterprise PlanType = "enterprise"
const PlanTypeEdu PlanType = "edu"
const PlanTypeUnknown PlanType = "unknown"

type CreditsSnapshot struct {
	// Balance corresponds to the JSON schema field "balance".
	Balance CreditsSnapshotBalance `json:"balance,omitempty"`

	// HasCredits corresponds to the JSON schema field "hasCredits".
	HasCredits bool `json:"hasCredits"`

	// Unlimited corresponds to the JSON schema field "unlimited".
	Unlimited bool `json:"unlimited"`
}

type CreditsSnapshotBalance *string

type RateLimitWindowWindowDurationMins *int

type RateLimitSnapshotLimitName *string

type RateLimitSnapshotPlanType_0 = PlanType

type RateLimitWindowResetsAt *int

type RateLimitSnapshotLimitId *string

type RateLimitWindow struct {
	// ResetsAt corresponds to the JSON schema field "resetsAt".
	ResetsAt RateLimitWindowResetsAt `json:"resetsAt,omitempty"`

	// UsedPercent corresponds to the JSON schema field "usedPercent".
	UsedPercent int `json:"usedPercent"`

	// WindowDurationMins corresponds to the JSON schema field "windowDurationMins".
	WindowDurationMins RateLimitWindowWindowDurationMins `json:"windowDurationMins,omitempty"`
}

type RateLimitSnapshotPrimary_0 = RateLimitWindow

type RateLimitSnapshotPrimary struct {
	// ResetsAt corresponds to the JSON schema field "resetsAt".
	ResetsAt RateLimitWindowResetsAt `json:"resetsAt,omitempty"`

	// UsedPercent corresponds to the JSON schema field "usedPercent".
	UsedPercent int `json:"usedPercent"`

	// WindowDurationMins corresponds to the JSON schema field "windowDurationMins".
	WindowDurationMins RateLimitWindowWindowDurationMins `json:"windowDurationMins,omitempty"`
}

type RateLimitSnapshotCredits struct {
	// Balance corresponds to the JSON schema field "balance".
	Balance CreditsSnapshotBalance `json:"balance,omitempty"`

	// HasCredits corresponds to the JSON schema field "hasCredits".
	HasCredits bool `json:"hasCredits"`

	// Unlimited corresponds to the JSON schema field "unlimited".
	Unlimited bool `json:"unlimited"`
}

type RateLimitSnapshotSecondary struct {
	// ResetsAt corresponds to the JSON schema field "resetsAt".
	ResetsAt RateLimitWindowResetsAt `json:"resetsAt,omitempty"`

	// UsedPercent corresponds to the JSON schema field "usedPercent".
	UsedPercent int `json:"usedPercent"`

	// WindowDurationMins corresponds to the JSON schema field "windowDurationMins".
	WindowDurationMins RateLimitWindowWindowDurationMins `json:"windowDurationMins,omitempty"`
}

type RateLimitSnapshot struct {
	// Credits corresponds to the JSON schema field "credits".
	Credits *RateLimitSnapshotCredits `json:"credits,omitempty"`

	// LimitId corresponds to the JSON schema field "limitId".
	LimitId RateLimitSnapshotLimitId `json:"limitId,omitempty"`

	// LimitName corresponds to the JSON schema field "limitName".
	LimitName RateLimitSnapshotLimitName `json:"limitName,omitempty"`

	// PlanType corresponds to the JSON schema field "planType".
	PlanType interface{} `json:"planType,omitempty"`

	// Primary corresponds to the JSON schema field "primary".
	Primary *RateLimitSnapshotPrimary `json:"primary,omitempty"`

	// Secondary corresponds to the JSON schema field "secondary".
	Secondary *RateLimitSnapshotSecondary `json:"secondary,omitempty"`
}

type AccountRateLimitsUpdatedNotification struct {
	// RateLimits corresponds to the JSON schema field "rateLimits".
	RateLimits RateLimitSnapshot `json:"rateLimits"`
}
