// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package server_request

type ApplyPatchApprovalParams struct {
	// Use to correlate this with [codex_core::protocol::PatchApplyBeginEvent] and
	// [codex_core::protocol::PatchApplyEndEvent].
	CallId string `json:"callId"`

	// ConversationId corresponds to the JSON schema field "conversationId".
	ConversationId ThreadId `json:"conversationId"`

	// FileChanges corresponds to the JSON schema field "fileChanges".
	FileChanges ApplyPatchApprovalParamsFileChanges `json:"fileChanges"`

	// When set, the agent is asking the user to allow writes under this root for the
	// remainder of the session (unclear if this is honored today).
	GrantRoot ApplyPatchApprovalParamsGrantRoot `json:"grantRoot,omitempty"`

	// Optional explanatory reason (e.g. request for extra write access).
	Reason ApplyPatchApprovalParamsReason `json:"reason,omitempty"`
}

type ApplyPatchApprovalParamsFileChanges map[string]FileChange

// When set, the agent is asking the user to allow writes under this root for the
// remainder of the session (unclear if this is honored today).
type ApplyPatchApprovalParamsGrantRoot *string

// Optional explanatory reason (e.g. request for extra write access).
type ApplyPatchApprovalParamsReason *string

type ChatgptAuthTokensRefreshParams struct {
	// Workspace/account identifier that Codex was previously using.
	//
	// Clients that manage multiple accounts/workspaces can use this as a hint to
	// refresh the token for the correct workspace.
	//
	// This may be `null` when the prior auth state did not include a workspace
	// identifier (`chatgpt_account_id`).
	PreviousAccountId ChatgptAuthTokensRefreshParamsPreviousAccountId `json:"previousAccountId,omitempty"`

	// Reason corresponds to the JSON schema field "reason".
	Reason ChatgptAuthTokensRefreshReason `json:"reason"`
}

// Workspace/account identifier that Codex was previously using.
//
// Clients that manage multiple accounts/workspaces can use this as a hint to
// refresh the token for the correct workspace.
//
// This may be `null` when the prior auth state did not include a workspace
// identifier (`chatgpt_account_id`).
type ChatgptAuthTokensRefreshParamsPreviousAccountId *string

type ChatgptAuthTokensRefreshReason interface{}

type CommandAction interface{}

type CommandExecutionRequestApprovalParams struct {
	// Unique identifier for this specific approval callback.
	//
	// For regular shell/unified_exec approvals, this is null.
	//
	// For zsh-exec-bridge subcommand approvals, multiple callbacks can belong to one
	// parent `itemId`, so `approvalId` is a distinct opaque callback id (a UUID) used
	// to disambiguate routing.
	ApprovalId CommandExecutionRequestApprovalParamsApprovalId `json:"approvalId,omitempty"`

	// The command to be executed.
	Command CommandExecutionRequestApprovalParamsCommand `json:"command,omitempty"`

	// Best-effort parsed command actions for friendly display.
	CommandActions *CommandExecutionRequestApprovalParamsCommandActions `json:"commandActions,omitempty"`

	// The command's working directory.
	Cwd CommandExecutionRequestApprovalParamsCwd `json:"cwd,omitempty"`

	// ItemId corresponds to the JSON schema field "itemId".
	ItemId string `json:"itemId"`

	// Optional proposed execpolicy amendment to allow similar commands without
	// prompting.
	ProposedExecpolicyAmendment *CommandExecutionRequestApprovalParamsProposedExecpolicyAmendment `json:"proposedExecpolicyAmendment,omitempty"`

	// Optional explanatory reason (e.g. request for network access).
	Reason CommandExecutionRequestApprovalParamsReason `json:"reason,omitempty"`

	// ThreadId corresponds to the JSON schema field "threadId".
	ThreadId string `json:"threadId"`

	// TurnId corresponds to the JSON schema field "turnId".
	TurnId string `json:"turnId"`
}

// Unique identifier for this specific approval callback.
//
// For regular shell/unified_exec approvals, this is null.
//
// For zsh-exec-bridge subcommand approvals, multiple callbacks can belong to one
// parent `itemId`, so `approvalId` is a distinct opaque callback id (a UUID) used
// to disambiguate routing.
type CommandExecutionRequestApprovalParamsApprovalId *string

// The command to be executed.
type CommandExecutionRequestApprovalParamsCommand *string

// Best-effort parsed command actions for friendly display.
type CommandExecutionRequestApprovalParamsCommandActions []CommandAction

// The command's working directory.
type CommandExecutionRequestApprovalParamsCwd *string

// Optional proposed execpolicy amendment to allow similar commands without
// prompting.
type CommandExecutionRequestApprovalParamsProposedExecpolicyAmendment []string

// Optional explanatory reason (e.g. request for network access).
type CommandExecutionRequestApprovalParamsReason *string

type DynamicToolCallParams struct {
	// Arguments corresponds to the JSON schema field "arguments".
	Arguments interface{} `json:"arguments"`

	// CallId corresponds to the JSON schema field "callId".
	CallId string `json:"callId"`

	// ThreadId corresponds to the JSON schema field "threadId".
	ThreadId string `json:"threadId"`

	// Tool corresponds to the JSON schema field "tool".
	Tool string `json:"tool"`

	// TurnId corresponds to the JSON schema field "turnId".
	TurnId string `json:"turnId"`
}

type ExecCommandApprovalParams struct {
	// Identifier for this specific approval callback.
	ApprovalId ExecCommandApprovalParamsApprovalId `json:"approvalId,omitempty"`

	// Use to correlate this with [codex_core::protocol::ExecCommandBeginEvent] and
	// [codex_core::protocol::ExecCommandEndEvent].
	CallId string `json:"callId"`

	// Command corresponds to the JSON schema field "command".
	Command []string `json:"command"`

	// ConversationId corresponds to the JSON schema field "conversationId".
	ConversationId ThreadId `json:"conversationId"`

	// Cwd corresponds to the JSON schema field "cwd".
	Cwd string `json:"cwd"`

	// ParsedCmd corresponds to the JSON schema field "parsedCmd".
	ParsedCmd []ParsedCommand `json:"parsedCmd"`

	// Reason corresponds to the JSON schema field "reason".
	Reason ExecCommandApprovalParamsReason `json:"reason,omitempty"`
}

// Identifier for this specific approval callback.
type ExecCommandApprovalParamsApprovalId *string

type ExecCommandApprovalParamsReason *string

type FileChange interface{}

type FileChangeRequestApprovalParams struct {
	// [UNSTABLE] When set, the agent is asking the user to allow writes under this
	// root for the remainder of the session (unclear if this is honored today).
	GrantRoot FileChangeRequestApprovalParamsGrantRoot `json:"grantRoot,omitempty"`

	// ItemId corresponds to the JSON schema field "itemId".
	ItemId string `json:"itemId"`

	// Optional explanatory reason (e.g. request for extra write access).
	Reason FileChangeRequestApprovalParamsReason `json:"reason,omitempty"`

	// ThreadId corresponds to the JSON schema field "threadId".
	ThreadId string `json:"threadId"`

	// TurnId corresponds to the JSON schema field "turnId".
	TurnId string `json:"turnId"`
}

// [UNSTABLE] When set, the agent is asking the user to allow writes under this
// root for the remainder of the session (unclear if this is honored today).
type FileChangeRequestApprovalParamsGrantRoot *string

// Optional explanatory reason (e.g. request for extra write access).
type FileChangeRequestApprovalParamsReason *string

type ParsedCommand interface{}

type RequestId interface{}

type ThreadId string

// EXPERIMENTAL. Defines a single selectable option for request_user_input.
type ToolRequestUserInputOption struct {
	// Description corresponds to the JSON schema field "description".
	Description string `json:"description"`

	// Label corresponds to the JSON schema field "label".
	Label string `json:"label"`
}

// EXPERIMENTAL. Params sent with a request_user_input event.
type ToolRequestUserInputParams struct {
	// ItemId corresponds to the JSON schema field "itemId".
	ItemId string `json:"itemId"`

	// Questions corresponds to the JSON schema field "questions".
	Questions []ToolRequestUserInputQuestion `json:"questions"`

	// ThreadId corresponds to the JSON schema field "threadId".
	ThreadId string `json:"threadId"`

	// TurnId corresponds to the JSON schema field "turnId".
	TurnId string `json:"turnId"`
}

// EXPERIMENTAL. Represents one request_user_input question and its required
// options.
type ToolRequestUserInputQuestion struct {
	// Header corresponds to the JSON schema field "header".
	Header string `json:"header"`

	// Id corresponds to the JSON schema field "id".
	Id string `json:"id"`

	// IsOther corresponds to the JSON schema field "isOther".
	IsOther bool `json:"isOther,omitempty"`

	// IsSecret corresponds to the JSON schema field "isSecret".
	IsSecret bool `json:"isSecret,omitempty"`

	// Options corresponds to the JSON schema field "options".
	Options *ToolRequestUserInputQuestionOptions `json:"options,omitempty"`

	// Question corresponds to the JSON schema field "question".
	Question string `json:"question"`
}

type ToolRequestUserInputQuestionOptions []ToolRequestUserInputOption
