// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package get_account_params

type GetAccountParams struct {
	// When `true`, requests a proactive token refresh before returning.
	//
	// In managed auth mode this triggers the normal refresh-token flow. In external
	// auth mode this flag is ignored. Clients should refresh tokens themselves and
	// call `account/login/start` with `chatgptAuthTokens`.
	RefreshToken bool `json:"refreshToken,omitempty"`
}
