// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package skills_list_params

type SkillsListExtraRootsForCwd struct {
	// Cwd corresponds to the JSON schema field "cwd".
	Cwd string `json:"cwd"`

	// ExtraUserRoots corresponds to the JSON schema field "extraUserRoots".
	ExtraUserRoots []string `json:"extraUserRoots"`
}

type SkillsListParams struct {
	// When empty, defaults to the current session working directory.
	Cwds []string `json:"cwds,omitempty"`

	// When true, bypass the skills cache and re-scan skills from disk.
	ForceReload *bool `json:"forceReload,omitempty"`

	// Optional per-cwd extra roots to scan as user-scoped skills.
	PerCwdExtraUserRoots *SkillsListParamsPerCwdExtraUserRoots `json:"perCwdExtraUserRoots,omitempty"`
}

// Optional per-cwd extra roots to scan as user-scoped skills.
type SkillsListParamsPerCwdExtraUserRoots []SkillsListExtraRootsForCwd
