// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package account_login_completed_notification

type AccountLoginCompletedNotification struct {
	// Error corresponds to the JSON schema field "error".
	Error AccountLoginCompletedNotificationError `json:"error,omitempty"`

	// LoginId corresponds to the JSON schema field "loginId".
	LoginId AccountLoginCompletedNotificationLoginId `json:"loginId,omitempty"`

	// Success corresponds to the JSON schema field "success".
	Success bool `json:"success"`
}

type AccountLoginCompletedNotificationError *string

type AccountLoginCompletedNotificationLoginId *string
