// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package thread_archived_notification

type ThreadArchivedNotification struct {
	// ThreadId corresponds to the JSON schema field "threadId".
	ThreadId string `json:"threadId"`
}
