// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package item_started_notification

type ByteRange struct {
	// End corresponds to the JSON schema field "end".
	End int `json:"end"`

	// Start corresponds to the JSON schema field "start".
	Start int `json:"start"`
}

type CollabAgentState struct {
	// Message corresponds to the JSON schema field "message".
	Message CollabAgentStateMessage `json:"message,omitempty"`

	// Status corresponds to the JSON schema field "status".
	Status CollabAgentStatus `json:"status"`
}

type CollabAgentStateMessage *string

type CollabAgentStatus string

const CollabAgentStatusCompleted CollabAgentStatus = "completed"
const CollabAgentStatusErrored CollabAgentStatus = "errored"
const CollabAgentStatusNotFound CollabAgentStatus = "notFound"
const CollabAgentStatusPendingInit CollabAgentStatus = "pendingInit"
const CollabAgentStatusRunning CollabAgentStatus = "running"
const CollabAgentStatusShutdown CollabAgentStatus = "shutdown"

type CollabAgentTool string

type CollabAgentToolCallStatus string

const CollabAgentToolCallStatusCompleted CollabAgentToolCallStatus = "completed"
const CollabAgentToolCallStatusFailed CollabAgentToolCallStatus = "failed"
const CollabAgentToolCallStatusInProgress CollabAgentToolCallStatus = "inProgress"
const CollabAgentToolCloseAgent CollabAgentTool = "closeAgent"
const CollabAgentToolResumeAgent CollabAgentTool = "resumeAgent"
const CollabAgentToolSendInput CollabAgentTool = "sendInput"
const CollabAgentToolSpawnAgent CollabAgentTool = "spawnAgent"
const CollabAgentToolWait CollabAgentTool = "wait"

type CommandAction interface{}

type CommandExecutionStatus string

const CommandExecutionStatusCompleted CommandExecutionStatus = "completed"
const CommandExecutionStatusDeclined CommandExecutionStatus = "declined"
const CommandExecutionStatusFailed CommandExecutionStatus = "failed"
const CommandExecutionStatusInProgress CommandExecutionStatus = "inProgress"

type FileUpdateChange struct {
	// Diff corresponds to the JSON schema field "diff".
	Diff string `json:"diff"`

	// Kind corresponds to the JSON schema field "kind".
	Kind PatchChangeKind `json:"kind"`

	// Path corresponds to the JSON schema field "path".
	Path string `json:"path"`
}

type ItemStartedNotification struct {
	// Item corresponds to the JSON schema field "item".
	Item ThreadItem `json:"item"`

	// ThreadId corresponds to the JSON schema field "threadId".
	ThreadId string `json:"threadId"`

	// TurnId corresponds to the JSON schema field "turnId".
	TurnId string `json:"turnId"`
}

type McpToolCallError struct {
	// Message corresponds to the JSON schema field "message".
	Message string `json:"message"`
}

type McpToolCallResult struct {
	// Content corresponds to the JSON schema field "content".
	Content []interface{} `json:"content"`

	// StructuredContent corresponds to the JSON schema field "structuredContent".
	StructuredContent interface{} `json:"structuredContent,omitempty"`
}

type McpToolCallStatus string

const McpToolCallStatusCompleted McpToolCallStatus = "completed"
const McpToolCallStatusFailed McpToolCallStatus = "failed"
const McpToolCallStatusInProgress McpToolCallStatus = "inProgress"

type PatchApplyStatus string

const PatchApplyStatusCompleted PatchApplyStatus = "completed"
const PatchApplyStatusDeclined PatchApplyStatus = "declined"
const PatchApplyStatusFailed PatchApplyStatus = "failed"
const PatchApplyStatusInProgress PatchApplyStatus = "inProgress"

type PatchChangeKind interface{}

type TextElement struct {
	// Byte range in the parent `text` buffer that this element occupies.
	ByteRange TextElementByteRange `json:"byteRange"`

	// Optional human-readable placeholder for the element, displayed in the UI.
	Placeholder TextElementPlaceholder `json:"placeholder,omitempty"`
}

// Byte range in the parent `text` buffer that this element occupies.
type TextElementByteRange struct {
	// End corresponds to the JSON schema field "end".
	End int `json:"end"`

	// Start corresponds to the JSON schema field "start".
	Start int `json:"start"`
}

// Optional human-readable placeholder for the element, displayed in the UI.
type TextElementPlaceholder *string

type ThreadItem interface{}

type UserInput interface{}

type WebSearchAction interface{}
