// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package model_list_response

// Canonical user-input modality tags advertised by a model.
type InputModality interface{}

type Model struct {
	// DefaultReasoningEffort corresponds to the JSON schema field
	// "defaultReasoningEffort".
	DefaultReasoningEffort ReasoningEffort `json:"defaultReasoningEffort"`

	// Description corresponds to the JSON schema field "description".
	Description string `json:"description"`

	// DisplayName corresponds to the JSON schema field "displayName".
	DisplayName string `json:"displayName"`

	// Hidden corresponds to the JSON schema field "hidden".
	Hidden bool `json:"hidden"`

	// Id corresponds to the JSON schema field "id".
	Id string `json:"id"`

	// InputModalities corresponds to the JSON schema field "inputModalities".
	InputModalities []InputModality `json:"inputModalities,omitempty"`

	// IsDefault corresponds to the JSON schema field "isDefault".
	IsDefault bool `json:"isDefault"`

	// Model corresponds to the JSON schema field "model".
	Model string `json:"model"`

	// SupportedReasoningEfforts corresponds to the JSON schema field
	// "supportedReasoningEfforts".
	SupportedReasoningEfforts []ReasoningEffortOption `json:"supportedReasoningEfforts"`

	// SupportsPersonality corresponds to the JSON schema field "supportsPersonality".
	SupportsPersonality bool `json:"supportsPersonality,omitempty"`

	// Upgrade corresponds to the JSON schema field "upgrade".
	Upgrade ModelUpgrade `json:"upgrade,omitempty"`
}

type ModelListResponse struct {
	// Data corresponds to the JSON schema field "data".
	Data []Model `json:"data"`

	// Opaque cursor to pass to the next call to continue after the last item. If
	// None, there are no more items to return.
	NextCursor ModelListResponseNextCursor `json:"nextCursor,omitempty"`
}

// Opaque cursor to pass to the next call to continue after the last item. If None,
// there are no more items to return.
type ModelListResponseNextCursor *string

type ModelUpgrade *string

type ReasoningEffort string

const ReasoningEffortHigh ReasoningEffort = "high"
const ReasoningEffortLow ReasoningEffort = "low"
const ReasoningEffortMedium ReasoningEffort = "medium"
const ReasoningEffortMinimal ReasoningEffort = "minimal"
const ReasoningEffortNone ReasoningEffort = "none"

type ReasoningEffortOption struct {
	// Description corresponds to the JSON schema field "description".
	Description string `json:"description"`

	// ReasoningEffort corresponds to the JSON schema field "reasoningEffort".
	ReasoningEffort ReasoningEffort `json:"reasoningEffort"`
}

const ReasoningEffortXhigh ReasoningEffort = "xhigh"
