// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package list_mcp_server_status_params

type ListMcpServerStatusParams struct {
	// Opaque pagination cursor returned by a previous call.
	Cursor ListMcpServerStatusParamsCursor `json:"cursor,omitempty"`

	// Optional page size; defaults to a server-defined value.
	Limit ListMcpServerStatusParamsLimit `json:"limit,omitempty"`
}

// Opaque pagination cursor returned by a previous call.
type ListMcpServerStatusParamsCursor *string

// Optional page size; defaults to a server-defined value.
type ListMcpServerStatusParamsLimit *int
