// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package turn_diff_updated_notification

// Notification that the turn-level unified diff has changed. Contains the latest
// aggregated diff across all file changes in the turn.
type TurnDiffUpdatedNotification struct {
	// Diff corresponds to the JSON schema field "diff".
	Diff string `json:"diff"`

	// ThreadId corresponds to the JSON schema field "threadId".
	ThreadId string `json:"threadId"`

	// TurnId corresponds to the JSON schema field "turnId".
	TurnId string `json:"turnId"`
}
