// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package model_rerouted_notification

type ModelRerouteReason string

const ModelRerouteReasonHighRiskCyberActivity ModelRerouteReason = "highRiskCyberActivity"

type ModelReroutedNotification struct {
	// FromModel corresponds to the JSON schema field "fromModel".
	FromModel string `json:"fromModel"`

	// Reason corresponds to the JSON schema field "reason".
	Reason ModelRerouteReason `json:"reason"`

	// ThreadId corresponds to the JSON schema field "threadId".
	ThreadId string `json:"threadId"`

	// ToModel corresponds to the JSON schema field "toModel".
	ToModel string `json:"toModel"`

	// TurnId corresponds to the JSON schema field "turnId".
	TurnId string `json:"turnId"`
}
