// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package error_notification

// This translation layer make sure that we expose codex error code in camel case.
//
// When an upstream HTTP status is available (for example, from the Responses API
// or a provider), it is forwarded in `httpStatusCode` on the relevant
// `codexErrorInfo` variant.
type CodexErrorInfo interface{}

type ErrorNotification struct {
	// Error corresponds to the JSON schema field "error".
	Error TurnError `json:"error"`

	// ThreadId corresponds to the JSON schema field "threadId".
	ThreadId string `json:"threadId"`

	// TurnId corresponds to the JSON schema field "turnId".
	TurnId string `json:"turnId"`

	// WillRetry corresponds to the JSON schema field "willRetry".
	WillRetry bool `json:"willRetry"`
}

type TurnError struct {
	// AdditionalDetails corresponds to the JSON schema field "additionalDetails".
	AdditionalDetails TurnErrorAdditionalDetails `json:"additionalDetails,omitempty"`

	// CodexErrorInfo corresponds to the JSON schema field "codexErrorInfo".
	CodexErrorInfo interface{} `json:"codexErrorInfo,omitempty"`

	// Message corresponds to the JSON schema field "message".
	Message string `json:"message"`
}

type TurnErrorAdditionalDetails *string
