// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package jsonrpc_request

// A request that expects a response.
type JSONRPCRequest struct {
	// Id corresponds to the JSON schema field "id".
	Id RequestId `json:"id"`

	// Method corresponds to the JSON schema field "method".
	Method string `json:"method"`

	// Params corresponds to the JSON schema field "params".
	Params interface{} `json:"params,omitempty"`
}

type RequestId interface{}
