// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package turn_interrupt_params

type TurnInterruptParams struct {
	// ThreadId corresponds to the JSON schema field "threadId".
	ThreadId string `json:"threadId"`

	// TurnId corresponds to the JSON schema field "turnId".
	TurnId string `json:"turnId"`
}
