// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package config_write_response

// A path that is guaranteed to be absolute and normalized (though it is not
// guaranteed to be canonicalized or exist on the filesystem).
//
// IMPORTANT: When deserializing an `AbsolutePathBuf`, a base path must be set
// using [AbsolutePathBufGuard::new]. If no base path is set, the deserialization
// will fail unless the path being deserialized is already absolute.
type AbsolutePathBuf string

type ConfigLayerMetadata struct {
	// Name corresponds to the JSON schema field "name".
	Name ConfigLayerSource `json:"name"`

	// Version corresponds to the JSON schema field "version".
	Version string `json:"version"`
}

type ConfigLayerSource interface{}

type OverriddenMetadata struct {
	// EffectiveValue corresponds to the JSON schema field "effectiveValue".
	EffectiveValue interface{} `json:"effectiveValue"`

	// Message corresponds to the JSON schema field "message".
	Message string `json:"message"`

	// OverridingLayer corresponds to the JSON schema field "overridingLayer".
	OverridingLayer ConfigLayerMetadata `json:"overridingLayer"`
}

type WriteStatus string

const WriteStatusOk WriteStatus = "ok"
const WriteStatusOkOverridden WriteStatus = "okOverridden"

type ConfigWriteResponseOverriddenMetadata_0 = OverriddenMetadata

type ConfigWriteResponse struct {
	// Canonical path to the config file that was written.
	FilePath interface{} `json:"filePath"`

	// OverriddenMetadata corresponds to the JSON schema field "overriddenMetadata".
	OverriddenMetadata *ConfigWriteResponseOverriddenMetadata `json:"overriddenMetadata,omitempty"`

	// Status corresponds to the JSON schema field "status".
	Status WriteStatus `json:"status"`

	// Version corresponds to the JSON schema field "version".
	Version string `json:"version"`
}

type ConfigWriteResponseOverriddenMetadata struct {
	// EffectiveValue corresponds to the JSON schema field "effectiveValue".
	EffectiveValue interface{} `json:"effectiveValue"`

	// Message corresponds to the JSON schema field "message".
	Message string `json:"message"`

	// OverridingLayer corresponds to the JSON schema field "overridingLayer".
	OverridingLayer ConfigLayerMetadata `json:"overridingLayer"`
}
