// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package thread_resume_params

type AskForApproval string

const AskForApprovalNever AskForApproval = "never"
const AskForApprovalOnFailure AskForApproval = "on-failure"
const AskForApprovalOnRequest AskForApproval = "on-request"
const AskForApprovalUntrusted AskForApproval = "untrusted"

type ContentItem interface{}

type FunctionCallOutputBody interface{}

// Responses API compatible content items that can be returned by a tool call. This
// is a subset of ContentItem with the types we support as function call outputs.
type FunctionCallOutputContentItem interface{}

// The payload we send back to OpenAI when reporting a tool call result.
//
// `body` serializes directly as the wire value for `function_call_output.output`.
// `success` remains internal metadata for downstream handling.
type FunctionCallOutputPayload struct {
	// Body corresponds to the JSON schema field "body".
	Body FunctionCallOutputBody `json:"body"`

	// Success corresponds to the JSON schema field "success".
	Success FunctionCallOutputPayloadSuccess `json:"success,omitempty"`
}

type FunctionCallOutputPayloadSuccess *bool

// Details of a ghost commit created from a repository state.
type GhostCommit struct {
	// Id corresponds to the JSON schema field "id".
	Id string `json:"id"`

	// Parent corresponds to the JSON schema field "parent".
	Parent GhostCommitParent `json:"parent,omitempty"`

	// PreexistingUntrackedDirs corresponds to the JSON schema field
	// "preexisting_untracked_dirs".
	PreexistingUntrackedDirs []string `json:"preexisting_untracked_dirs"`

	// PreexistingUntrackedFiles corresponds to the JSON schema field
	// "preexisting_untracked_files".
	PreexistingUntrackedFiles []string `json:"preexisting_untracked_files"`
}

type GhostCommitParent *string

type LocalShellAction interface{}

type LocalShellStatus string

const LocalShellStatusCompleted LocalShellStatus = "completed"
const LocalShellStatusInProgress LocalShellStatus = "in_progress"
const LocalShellStatusIncomplete LocalShellStatus = "incomplete"

// Classifies an assistant message as interim commentary or final answer text.
//
// Providers do not emit this consistently, so callers must treat `None` as "phase
// unknown" and keep compatibility behavior for legacy models.
type MessagePhase interface{}

type Personality string

const PersonalityFriendly Personality = "friendly"

type ThreadResumeParamsApprovalPolicy_0 = AskForApproval

const PersonalityPragmatic Personality = "pragmatic"

type ReasoningItemContent interface{}

type ReasoningItemReasoningSummary interface{}

type ResponseItem interface{}

type SandboxMode string

const SandboxModeReadOnly SandboxMode = "read-only"
const SandboxModeWorkspaceWrite SandboxMode = "workspace-write"
const SandboxModeDangerFullAccess SandboxMode = "danger-full-access"

type WebSearchAction interface{}

const PersonalityNone Personality = "none"

type ThreadResumeParamsBaseInstructions *string

type ThreadResumeParamsConfig map[string]interface{}

type ThreadResumeParamsCwd *string

type ThreadResumeParamsDeveloperInstructions *string

// Configuration overrides for the resumed thread, if any.
type ThreadResumeParamsModel *string

type ThreadResumeParamsModelProvider *string

type ThreadResumeParamsPersonality_0 = Personality

type ThreadResumeParamsSandbox_0 = SandboxMode

// There are three ways to resume a thread: 1. By thread_id: load the thread from
// disk by thread_id and resume it. 2. By history: instantiate the thread from
// memory and resume it. 3. By path: load the thread from disk by path and resume
// it.
//
// The precedence is: history > path > thread_id. If using history or path, the
// thread_id param will be ignored.
//
// Prefer using thread_id whenever possible.
type ThreadResumeParams struct {
	// ApprovalPolicy corresponds to the JSON schema field "approvalPolicy".
	ApprovalPolicy interface{} `json:"approvalPolicy,omitempty"`

	// BaseInstructions corresponds to the JSON schema field "baseInstructions".
	BaseInstructions ThreadResumeParamsBaseInstructions `json:"baseInstructions,omitempty"`

	// Config corresponds to the JSON schema field "config".
	Config *ThreadResumeParamsConfig `json:"config,omitempty"`

	// Cwd corresponds to the JSON schema field "cwd".
	Cwd ThreadResumeParamsCwd `json:"cwd,omitempty"`

	// DeveloperInstructions corresponds to the JSON schema field
	// "developerInstructions".
	DeveloperInstructions ThreadResumeParamsDeveloperInstructions `json:"developerInstructions,omitempty"`

	// Configuration overrides for the resumed thread, if any.
	Model ThreadResumeParamsModel `json:"model,omitempty"`

	// ModelProvider corresponds to the JSON schema field "modelProvider".
	ModelProvider ThreadResumeParamsModelProvider `json:"modelProvider,omitempty"`

	// Personality corresponds to the JSON schema field "personality".
	Personality interface{} `json:"personality,omitempty"`

	// Sandbox corresponds to the JSON schema field "sandbox".
	Sandbox interface{} `json:"sandbox,omitempty"`

	// ThreadId corresponds to the JSON schema field "threadId".
	ThreadId string `json:"threadId"`
}
