// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package turn_steer_response

type TurnSteerResponse struct {
	// TurnId corresponds to the JSON schema field "turnId".
	TurnId string `json:"turnId"`
}
