// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package deprecation_notice_notification

type DeprecationNoticeNotification struct {
	// Optional extra guidance, such as migration steps or rationale.
	Details DeprecationNoticeNotificationDetails `json:"details,omitempty"`

	// Concise summary of what is deprecated.
	Summary string `json:"summary"`
}

// Optional extra guidance, such as migration steps or rationale.
type DeprecationNoticeNotificationDetails *string
