// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package turn_start_params

// A path that is guaranteed to be absolute and normalized (though it is not
// guaranteed to be canonicalized or exist on the filesystem).
//
// IMPORTANT: When deserializing an `AbsolutePathBuf`, a base path must be set
// using [AbsolutePathBufGuard::new]. If no base path is set, the deserialization
// will fail unless the path being deserialized is already absolute.
type AbsolutePathBuf string

type AskForApproval string

const AskForApprovalNever AskForApproval = "never"
const AskForApprovalOnFailure AskForApproval = "on-failure"
const AskForApprovalOnRequest AskForApproval = "on-request"
const AskForApprovalUntrusted AskForApproval = "untrusted"

type ByteRange struct {
	// End corresponds to the JSON schema field "end".
	End int `json:"end"`

	// Start corresponds to the JSON schema field "start".
	Start int `json:"start"`
}

// Collaboration mode for a Codex session.
type CollaborationMode struct {
	// Mode corresponds to the JSON schema field "mode".
	Mode ModeKind `json:"mode"`

	// Settings corresponds to the JSON schema field "settings".
	Settings Settings `json:"settings"`
}

type ModeKind string

const ModeKindDefault ModeKind = "default"
const ModeKindPlan ModeKind = "plan"

type NetworkAccess string

const NetworkAccessEnabled NetworkAccess = "enabled"
const NetworkAccessRestricted NetworkAccess = "restricted"

type Personality string

const PersonalityFriendly Personality = "friendly"
const PersonalityNone Personality = "none"
const PersonalityPragmatic Personality = "pragmatic"

type ReadOnlyAccess interface{}

type ReasoningEffort string

const ReasoningEffortHigh ReasoningEffort = "high"
const ReasoningEffortLow ReasoningEffort = "low"
const ReasoningEffortMedium ReasoningEffort = "medium"
const ReasoningEffortMinimal ReasoningEffort = "minimal"
const ReasoningEffortNone ReasoningEffort = "none"
const ReasoningEffortXhigh ReasoningEffort = "xhigh"

// A summary of the reasoning performed by the model. This can be useful for
// debugging and understanding the model's reasoning process. See
// https://platform.openai.com/docs/guides/reasoning?api-mode=responses#reasoning-summaries
type ReasoningSummary interface{}

type SandboxPolicy interface{}

// Settings for a collaboration mode.
type Settings struct {
	// DeveloperInstructions corresponds to the JSON schema field
	// "developer_instructions".
	DeveloperInstructions SettingsDeveloperInstructions `json:"developer_instructions,omitempty"`

	// Model corresponds to the JSON schema field "model".
	Model string `json:"model"`

	// ReasoningEffort corresponds to the JSON schema field "reasoning_effort".
	ReasoningEffort interface{} `json:"reasoning_effort,omitempty"`
}

type SettingsDeveloperInstructions *string

type TextElement struct {
	// Byte range in the parent `text` buffer that this element occupies.
	ByteRange TextElementByteRange `json:"byteRange"`

	// Optional human-readable placeholder for the element, displayed in the UI.
	Placeholder TextElementPlaceholder `json:"placeholder,omitempty"`
}

// Byte range in the parent `text` buffer that this element occupies.
type TextElementByteRange struct {
	// End corresponds to the JSON schema field "end".
	End int `json:"end"`

	// Start corresponds to the JSON schema field "start".
	Start int `json:"start"`
}

// Optional human-readable placeholder for the element, displayed in the UI.
type TextElementPlaceholder *string

type TurnStartParams struct {
	// Override the approval policy for this turn and subsequent turns.
	ApprovalPolicy interface{} `json:"approvalPolicy,omitempty"`

	// Override the working directory for this turn and subsequent turns.
	Cwd TurnStartParamsCwd `json:"cwd,omitempty"`

	// Override the reasoning effort for this turn and subsequent turns.
	Effort interface{} `json:"effort,omitempty"`

	// Input corresponds to the JSON schema field "input".
	Input []UserInput `json:"input"`

	// Override the model for this turn and subsequent turns.
	Model TurnStartParamsModel `json:"model,omitempty"`

	// Optional JSON Schema used to constrain the final assistant message for this
	// turn.
	OutputSchema interface{} `json:"outputSchema,omitempty"`

	// Override the personality for this turn and subsequent turns.
	Personality interface{} `json:"personality,omitempty"`

	// Override the sandbox policy for this turn and subsequent turns.
	SandboxPolicy interface{} `json:"sandboxPolicy,omitempty"`

	// Override the reasoning summary for this turn and subsequent turns.
	Summary interface{} `json:"summary,omitempty"`

	// ThreadId corresponds to the JSON schema field "threadId".
	ThreadId string `json:"threadId"`
}

// Override the working directory for this turn and subsequent turns.
type TurnStartParamsCwd *string

// Override the model for this turn and subsequent turns.
type TurnStartParamsModel *string

type UserInput interface{}

type TurnStartParamsEffort_0 = ReasoningEffort

type TurnStartParamsApprovalPolicy_0 = AskForApproval

type TurnStartParamsPersonality_0 = Personality

type SettingsReasoningEffort_0 = ReasoningEffort
