// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package config_value_write_params

type ConfigValueWriteParams struct {
	// ExpectedVersion corresponds to the JSON schema field "expectedVersion".
	ExpectedVersion ConfigValueWriteParamsExpectedVersion `json:"expectedVersion,omitempty"`

	// Path to the config file to write; defaults to the user's `config.toml` when
	// omitted.
	FilePath ConfigValueWriteParamsFilePath `json:"filePath,omitempty"`

	// KeyPath corresponds to the JSON schema field "keyPath".
	KeyPath string `json:"keyPath"`

	// MergeStrategy corresponds to the JSON schema field "mergeStrategy".
	MergeStrategy MergeStrategy `json:"mergeStrategy"`

	// Value corresponds to the JSON schema field "value".
	Value interface{} `json:"value"`
}

type ConfigValueWriteParamsExpectedVersion *string

// Path to the config file to write; defaults to the user's `config.toml` when
// omitted.
type ConfigValueWriteParamsFilePath *string

type MergeStrategy string

const MergeStrategyReplace MergeStrategy = "replace"
const MergeStrategyUpsert MergeStrategy = "upsert"
