// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package tool_request_user_input_response

// EXPERIMENTAL. Captures a user's answer to a request_user_input question.
type ToolRequestUserInputAnswer struct {
	// Answers corresponds to the JSON schema field "answers".
	Answers []string `json:"answers"`
}

// EXPERIMENTAL. Response payload mapping question ids to answers.
type ToolRequestUserInputResponse struct {
	// Answers corresponds to the JSON schema field "answers".
	Answers ToolRequestUserInputResponseAnswers `json:"answers"`
}

type ToolRequestUserInputResponseAnswers map[string]ToolRequestUserInputAnswer
