// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package file_change_request_approval_response

type FileChangeApprovalDecision interface{}

type FileChangeRequestApprovalResponse struct {
	// Decision corresponds to the JSON schema field "decision".
	Decision FileChangeApprovalDecision `json:"decision"`
}
