// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package feedback_upload_params

type FeedbackUploadParams struct {
	// Classification corresponds to the JSON schema field "classification".
	Classification string `json:"classification"`

	// IncludeLogs corresponds to the JSON schema field "includeLogs".
	IncludeLogs bool `json:"includeLogs"`

	// Reason corresponds to the JSON schema field "reason".
	Reason FeedbackUploadParamsReason `json:"reason,omitempty"`

	// ThreadId corresponds to the JSON schema field "threadId".
	ThreadId FeedbackUploadParamsThreadId `json:"threadId,omitempty"`
}

type FeedbackUploadParamsReason *string

type FeedbackUploadParamsThreadId *string
