// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package mcp_server_oauth_login_response

type McpServerOauthLoginResponse struct {
	// AuthorizationUrl corresponds to the JSON schema field "authorizationUrl".
	AuthorizationUrl string `json:"authorizationUrl"`
}
