// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package turn_steer_params

type ByteRange struct {
	// End corresponds to the JSON schema field "end".
	End int `json:"end"`

	// Start corresponds to the JSON schema field "start".
	Start int `json:"start"`
}

type TextElement struct {
	// Byte range in the parent `text` buffer that this element occupies.
	ByteRange TextElementByteRange `json:"byteRange"`

	// Optional human-readable placeholder for the element, displayed in the UI.
	Placeholder TextElementPlaceholder `json:"placeholder,omitempty"`
}

// Byte range in the parent `text` buffer that this element occupies.
type TextElementByteRange struct {
	// End corresponds to the JSON schema field "end".
	End int `json:"end"`

	// Start corresponds to the JSON schema field "start".
	Start int `json:"start"`
}

// Optional human-readable placeholder for the element, displayed in the UI.
type TextElementPlaceholder *string

type TurnSteerParams struct {
	// Required active turn id precondition. The request fails when it does not match
	// the currently active turn.
	ExpectedTurnId string `json:"expectedTurnId"`

	// Input corresponds to the JSON schema field "input".
	Input []UserInput `json:"input"`

	// ThreadId corresponds to the JSON schema field "threadId".
	ThreadId string `json:"threadId"`
}

type UserInput interface{}
