// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package fuzzy_file_search_session_updated_notification

// Superset of [`codex_file_search::FileMatch`]
type FuzzyFileSearchResult struct {
	// FileName corresponds to the JSON schema field "file_name".
	FileName string `json:"file_name"`

	// Indices corresponds to the JSON schema field "indices".
	Indices *FuzzyFileSearchResultIndices `json:"indices,omitempty"`

	// Path corresponds to the JSON schema field "path".
	Path string `json:"path"`

	// Root corresponds to the JSON schema field "root".
	Root string `json:"root"`

	// Score corresponds to the JSON schema field "score".
	Score int `json:"score"`
}

type FuzzyFileSearchResultIndices []int

type FuzzyFileSearchSessionUpdatedNotification struct {
	// Files corresponds to the JSON schema field "files".
	Files []FuzzyFileSearchResult `json:"files"`

	// Query corresponds to the JSON schema field "query".
	Query string `json:"query"`

	// SessionId corresponds to the JSON schema field "sessionId".
	SessionId string `json:"sessionId"`
}
