// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package fuzzy_file_search_params

type FuzzyFileSearchParams struct {
	// CancellationToken corresponds to the JSON schema field "cancellationToken".
	CancellationToken FuzzyFileSearchParamsCancellationToken `json:"cancellationToken,omitempty"`

	// Query corresponds to the JSON schema field "query".
	Query string `json:"query"`

	// Roots corresponds to the JSON schema field "roots".
	Roots []string `json:"roots"`
}

type FuzzyFileSearchParamsCancellationToken *string
