// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package jsonrpc_error

// A response to a request that indicates an error occurred.
type JSONRPCError struct {
	// Error corresponds to the JSON schema field "error".
	Error JSONRPCErrorError `json:"error"`

	// Id corresponds to the JSON schema field "id".
	Id RequestId `json:"id"`
}

type JSONRPCErrorError struct {
	// Code corresponds to the JSON schema field "code".
	Code int `json:"code"`

	// Data corresponds to the JSON schema field "data".
	Data interface{} `json:"data,omitempty"`

	// Message corresponds to the JSON schema field "message".
	Message string `json:"message"`
}

type RequestId interface{}
