// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package skills_remote_read_params

type HazelnutScope string

const HazelnutScopeAllShared HazelnutScope = "all-shared"
const HazelnutScopeExample HazelnutScope = "example"
const HazelnutScopePersonal HazelnutScope = "personal"
const HazelnutScopeWorkspaceShared HazelnutScope = "workspace-shared"

type ProductSurface string

const ProductSurfaceApi ProductSurface = "api"
const ProductSurfaceAtlas ProductSurface = "atlas"
const ProductSurfaceChatgpt ProductSurface = "chatgpt"
const ProductSurfaceCodex ProductSurface = "codex"

type SkillsRemoteReadParams struct {
	// Enabled corresponds to the JSON schema field "enabled".
	Enabled bool `json:"enabled,omitempty"`

	// HazelnutScope corresponds to the JSON schema field "hazelnutScope".
	HazelnutScope interface{} `json:"hazelnutScope,omitempty"`

	// ProductSurface corresponds to the JSON schema field "productSurface".
	ProductSurface interface{} `json:"productSurface,omitempty"`
}
