// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package thread_loaded_list_response

type ThreadLoadedListResponse struct {
	// Thread ids for sessions currently loaded in memory.
	Data []string `json:"data"`

	// Opaque cursor to pass to the next call to continue after the last item. if
	// None, there are no more items to return.
	NextCursor ThreadLoadedListResponseNextCursor `json:"nextCursor,omitempty"`
}

// Opaque cursor to pass to the next call to continue after the last item. if None,
// there are no more items to return.
type ThreadLoadedListResponseNextCursor *string
