// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package chatgpt_auth_tokens_refresh_params

type ChatgptAuthTokensRefreshParams struct {
	// Workspace/account identifier that Codex was previously using.
	//
	// Clients that manage multiple accounts/workspaces can use this as a hint to
	// refresh the token for the correct workspace.
	//
	// This may be `null` when the prior auth state did not include a workspace
	// identifier (`chatgpt_account_id`).
	PreviousAccountId ChatgptAuthTokensRefreshParamsPreviousAccountId `json:"previousAccountId,omitempty"`

	// Reason corresponds to the JSON schema field "reason".
	Reason ChatgptAuthTokensRefreshReason `json:"reason"`
}

// Workspace/account identifier that Codex was previously using.
//
// Clients that manage multiple accounts/workspaces can use this as a hint to
// refresh the token for the correct workspace.
//
// This may be `null` when the prior auth state did not include a workspace
// identifier (`chatgpt_account_id`).
type ChatgptAuthTokensRefreshParamsPreviousAccountId *string

type ChatgptAuthTokensRefreshReason interface{}
