// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package jsonrpc_message

// A response to a request that indicates an error occurred.
type JSONRPCError struct {
	// Error corresponds to the JSON schema field "error".
	Error JSONRPCErrorError `json:"error"`

	// Id corresponds to the JSON schema field "id".
	Id RequestId `json:"id"`
}

type JSONRPCErrorError struct {
	// Code corresponds to the JSON schema field "code".
	Code int `json:"code"`

	// Data corresponds to the JSON schema field "data".
	Data interface{} `json:"data,omitempty"`

	// Message corresponds to the JSON schema field "message".
	Message string `json:"message"`
}

// A notification which does not expect a response.
type JSONRPCNotification struct {
	// Method corresponds to the JSON schema field "method".
	Method string `json:"method"`

	// Params corresponds to the JSON schema field "params".
	Params interface{} `json:"params,omitempty"`
}

// A request that expects a response.
type JSONRPCRequest struct {
	// Id corresponds to the JSON schema field "id".
	Id RequestId `json:"id"`

	// Method corresponds to the JSON schema field "method".
	Method string `json:"method"`

	// Params corresponds to the JSON schema field "params".
	Params interface{} `json:"params,omitempty"`
}

// A successful (non-error) response to a request.
type JSONRPCResponse struct {
	// Id corresponds to the JSON schema field "id".
	Id RequestId `json:"id"`

	// Result corresponds to the JSON schema field "result".
	Result interface{} `json:"result"`
}

type RequestId interface{}
