// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package exec_command_approval_params

type ExecCommandApprovalParams struct {
	// Identifier for this specific approval callback.
	ApprovalId ExecCommandApprovalParamsApprovalId `json:"approvalId,omitempty"`

	// Use to correlate this with [codex_core::protocol::ExecCommandBeginEvent] and
	// [codex_core::protocol::ExecCommandEndEvent].
	CallId string `json:"callId"`

	// Command corresponds to the JSON schema field "command".
	Command []string `json:"command"`

	// ConversationId corresponds to the JSON schema field "conversationId".
	ConversationId ThreadId `json:"conversationId"`

	// Cwd corresponds to the JSON schema field "cwd".
	Cwd string `json:"cwd"`

	// ParsedCmd corresponds to the JSON schema field "parsedCmd".
	ParsedCmd []ParsedCommand `json:"parsedCmd"`

	// Reason corresponds to the JSON schema field "reason".
	Reason ExecCommandApprovalParamsReason `json:"reason,omitempty"`
}

// Identifier for this specific approval callback.
type ExecCommandApprovalParamsApprovalId *string

type ExecCommandApprovalParamsReason *string

type ParsedCommand interface{}

type ThreadId string
