// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package get_account_response

type Account interface{}

type GetAccountResponse struct {
	// Account corresponds to the JSON schema field "account".
	Account interface{} `json:"account,omitempty"`

	// RequiresOpenaiAuth corresponds to the JSON schema field "requiresOpenaiAuth".
	RequiresOpenaiAuth bool `json:"requiresOpenaiAuth"`
}

type PlanType string

const PlanTypeBusiness PlanType = "business"
const PlanTypeEdu PlanType = "edu"
const PlanTypeEnterprise PlanType = "enterprise"
const PlanTypeFree PlanType = "free"
const PlanTypeGo PlanType = "go"
const PlanTypePlus PlanType = "plus"
const PlanTypePro PlanType = "pro"
const PlanTypeTeam PlanType = "team"
const PlanTypeUnknown PlanType = "unknown"
