// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package command_exec_response

type CommandExecResponse struct {
	// ExitCode corresponds to the JSON schema field "exitCode".
	ExitCode int `json:"exitCode"`

	// Stderr corresponds to the JSON schema field "stderr".
	Stderr string `json:"stderr"`

	// Stdout corresponds to the JSON schema field "stdout".
	Stdout string `json:"stdout"`
}
