// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package raw_response_item_completed_notification

type ContentItem interface{}

type FunctionCallOutputBody interface{}

// Responses API compatible content items that can be returned by a tool call. This
// is a subset of ContentItem with the types we support as function call outputs.
type FunctionCallOutputContentItem interface{}

// The payload we send back to OpenAI when reporting a tool call result.
//
// `body` serializes directly as the wire value for `function_call_output.output`.
// `success` remains internal metadata for downstream handling.
type FunctionCallOutputPayload struct {
	// Body corresponds to the JSON schema field "body".
	Body FunctionCallOutputBody `json:"body"`

	// Success corresponds to the JSON schema field "success".
	Success FunctionCallOutputPayloadSuccess `json:"success,omitempty"`
}

type FunctionCallOutputPayloadSuccess *bool

// Details of a ghost commit created from a repository state.
type GhostCommit struct {
	// Id corresponds to the JSON schema field "id".
	Id string `json:"id"`

	// Parent corresponds to the JSON schema field "parent".
	Parent GhostCommitParent `json:"parent,omitempty"`

	// PreexistingUntrackedDirs corresponds to the JSON schema field
	// "preexisting_untracked_dirs".
	PreexistingUntrackedDirs []string `json:"preexisting_untracked_dirs"`

	// PreexistingUntrackedFiles corresponds to the JSON schema field
	// "preexisting_untracked_files".
	PreexistingUntrackedFiles []string `json:"preexisting_untracked_files"`
}

type GhostCommitParent *string

type LocalShellAction interface{}

type LocalShellStatus string

const LocalShellStatusCompleted LocalShellStatus = "completed"
const LocalShellStatusInProgress LocalShellStatus = "in_progress"
const LocalShellStatusIncomplete LocalShellStatus = "incomplete"

// Classifies an assistant message as interim commentary or final answer text.
//
// Providers do not emit this consistently, so callers must treat `None` as "phase
// unknown" and keep compatibility behavior for legacy models.
type MessagePhase interface{}

type RawResponseItemCompletedNotification struct {
	// Item corresponds to the JSON schema field "item".
	Item ResponseItem `json:"item"`

	// ThreadId corresponds to the JSON schema field "threadId".
	ThreadId string `json:"threadId"`

	// TurnId corresponds to the JSON schema field "turnId".
	TurnId string `json:"turnId"`
}

type ReasoningItemContent interface{}

type ReasoningItemReasoningSummary interface{}

type ResponseItem interface{}

type WebSearchAction interface{}
