// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package experimental_feature_list_params

type ExperimentalFeatureListParams struct {
	// Opaque pagination cursor returned by a previous call.
	Cursor ExperimentalFeatureListParamsCursor `json:"cursor,omitempty"`

	// Optional page size; defaults to a reasonable server-side value.
	Limit ExperimentalFeatureListParamsLimit `json:"limit,omitempty"`
}

// Opaque pagination cursor returned by a previous call.
type ExperimentalFeatureListParamsCursor *string

// Optional page size; defaults to a reasonable server-side value.
type ExperimentalFeatureListParamsLimit *int
