// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package apply_patch_approval_params

type ApplyPatchApprovalParams struct {
	// Use to correlate this with [codex_core::protocol::PatchApplyBeginEvent] and
	// [codex_core::protocol::PatchApplyEndEvent].
	CallId string `json:"callId"`

	// ConversationId corresponds to the JSON schema field "conversationId".
	ConversationId ThreadId `json:"conversationId"`

	// FileChanges corresponds to the JSON schema field "fileChanges".
	FileChanges ApplyPatchApprovalParamsFileChanges `json:"fileChanges"`

	// When set, the agent is asking the user to allow writes under this root for the
	// remainder of the session (unclear if this is honored today).
	GrantRoot ApplyPatchApprovalParamsGrantRoot `json:"grantRoot,omitempty"`

	// Optional explanatory reason (e.g. request for extra write access).
	Reason ApplyPatchApprovalParamsReason `json:"reason,omitempty"`
}

type ApplyPatchApprovalParamsFileChanges map[string]FileChange

// When set, the agent is asking the user to allow writes under this root for the
// remainder of the session (unclear if this is honored today).
type ApplyPatchApprovalParamsGrantRoot *string

// Optional explanatory reason (e.g. request for extra write access).
type ApplyPatchApprovalParamsReason *string

type FileChange interface{}

type ThreadId string
