// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package jsonrpc_notification

// A notification which does not expect a response.
type JSONRPCNotification struct {
	// Method corresponds to the JSON schema field "method".
	Method string `json:"method"`

	// Params corresponds to the JSON schema field "params".
	Params interface{} `json:"params,omitempty"`
}
