// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package command_exec_params

// A path that is guaranteed to be absolute and normalized (though it is not
// guaranteed to be canonicalized or exist on the filesystem).
//
// IMPORTANT: When deserializing an `AbsolutePathBuf`, a base path must be set
// using [AbsolutePathBufGuard::new]. If no base path is set, the deserialization
// will fail unless the path being deserialized is already absolute.
type AbsolutePathBuf string

type CommandExecParams struct {
	// Command corresponds to the JSON schema field "command".
	Command []string `json:"command"`

	// Cwd corresponds to the JSON schema field "cwd".
	Cwd CommandExecParamsCwd `json:"cwd,omitempty"`

	// SandboxPolicy corresponds to the JSON schema field "sandboxPolicy".
	SandboxPolicy interface{} `json:"sandboxPolicy,omitempty"`

	// TimeoutMs corresponds to the JSON schema field "timeoutMs".
	TimeoutMs CommandExecParamsTimeoutMs `json:"timeoutMs,omitempty"`
}

type CommandExecParamsCwd *string

type CommandExecParamsTimeoutMs *int

type NetworkAccess string

const NetworkAccessEnabled NetworkAccess = "enabled"
const NetworkAccessRestricted NetworkAccess = "restricted"

type ReadOnlyAccess interface{}

type SandboxPolicy interface{}
