// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package thread_archive_params

type ThreadArchiveParams struct {
	// ThreadId corresponds to the JSON schema field "threadId".
	ThreadId string `json:"threadId"`
}
