// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package app_list_updated_notification

// EXPERIMENTAL - app metadata returned by app-list APIs.
type AppBranding struct {
	// Category corresponds to the JSON schema field "category".
	Category AppBrandingCategory `json:"category,omitempty"`

	// Developer corresponds to the JSON schema field "developer".
	Developer AppBrandingDeveloper `json:"developer,omitempty"`

	// IsDiscoverableApp corresponds to the JSON schema field "isDiscoverableApp".
	IsDiscoverableApp bool `json:"isDiscoverableApp"`

	// PrivacyPolicy corresponds to the JSON schema field "privacyPolicy".
	PrivacyPolicy AppBrandingPrivacyPolicy `json:"privacyPolicy,omitempty"`

	// TermsOfService corresponds to the JSON schema field "termsOfService".
	TermsOfService AppBrandingTermsOfService `json:"termsOfService,omitempty"`

	// Website corresponds to the JSON schema field "website".
	Website AppBrandingWebsite `json:"website,omitempty"`
}

type AppBrandingCategory *string

type AppBrandingDeveloper *string

type AppBrandingPrivacyPolicy *string

type AppBrandingTermsOfService *string

type AppBrandingWebsite *string

// EXPERIMENTAL - app metadata returned by app-list APIs.
type AppInfo struct {
	// AppMetadata corresponds to the JSON schema field "appMetadata".
	AppMetadata *AppInfoAppMetadata `json:"appMetadata,omitempty"`

	// Branding corresponds to the JSON schema field "branding".
	Branding *AppInfoBranding `json:"branding,omitempty"`

	// Description corresponds to the JSON schema field "description".
	Description AppInfoDescription `json:"description,omitempty"`

	// DistributionChannel corresponds to the JSON schema field "distributionChannel".
	DistributionChannel AppInfoDistributionChannel `json:"distributionChannel,omitempty"`

	// Id corresponds to the JSON schema field "id".
	Id string `json:"id"`

	// InstallUrl corresponds to the JSON schema field "installUrl".
	InstallUrl AppInfoInstallUrl `json:"installUrl,omitempty"`

	// IsAccessible corresponds to the JSON schema field "isAccessible".
	IsAccessible bool `json:"isAccessible,omitempty"`

	// Whether this app is enabled in config.toml. Example: ```toml [apps.bad_app]
	// enabled = false ```
	IsEnabled bool `json:"isEnabled,omitempty"`

	// Labels corresponds to the JSON schema field "labels".
	Labels *AppInfoLabels `json:"labels,omitempty"`

	// LogoUrl corresponds to the JSON schema field "logoUrl".
	LogoUrl AppInfoLogoUrl `json:"logoUrl,omitempty"`

	// LogoUrlDark corresponds to the JSON schema field "logoUrlDark".
	LogoUrlDark AppInfoLogoUrlDark `json:"logoUrlDark,omitempty"`

	// Name corresponds to the JSON schema field "name".
	Name string `json:"name"`
}

type AppInfoAppMetadata struct {
	// Categories corresponds to the JSON schema field "categories".
	Categories *AppMetadataCategories `json:"categories,omitempty"`

	// Developer corresponds to the JSON schema field "developer".
	Developer AppMetadataDeveloper `json:"developer,omitempty"`

	// FirstPartyRequiresInstall corresponds to the JSON schema field
	// "firstPartyRequiresInstall".
	FirstPartyRequiresInstall AppMetadataFirstPartyRequiresInstall `json:"firstPartyRequiresInstall,omitempty"`

	// FirstPartyType corresponds to the JSON schema field "firstPartyType".
	FirstPartyType AppMetadataFirstPartyType `json:"firstPartyType,omitempty"`

	// Review corresponds to the JSON schema field "review".
	Review *AppInfoAppMetadataReview `json:"review,omitempty"`

	// Screenshots corresponds to the JSON schema field "screenshots".
	Screenshots *AppMetadataScreenshots `json:"screenshots,omitempty"`

	// SeoDescription corresponds to the JSON schema field "seoDescription".
	SeoDescription AppMetadataSeoDescription `json:"seoDescription,omitempty"`

	// ShowInComposerWhenUnlinked corresponds to the JSON schema field
	// "showInComposerWhenUnlinked".
	ShowInComposerWhenUnlinked AppMetadataShowInComposerWhenUnlinked `json:"showInComposerWhenUnlinked,omitempty"`

	// SubCategories corresponds to the JSON schema field "subCategories".
	SubCategories *AppMetadataSubCategories `json:"subCategories,omitempty"`

	// Version corresponds to the JSON schema field "version".
	Version AppMetadataVersion `json:"version,omitempty"`

	// VersionId corresponds to the JSON schema field "versionId".
	VersionId AppMetadataVersionId `json:"versionId,omitempty"`

	// VersionNotes corresponds to the JSON schema field "versionNotes".
	VersionNotes AppMetadataVersionNotes `json:"versionNotes,omitempty"`
}

type AppInfoAppMetadataReview struct {
	// Status corresponds to the JSON schema field "status".
	Status string `json:"status"`
}

// EXPERIMENTAL - app metadata returned by app-list APIs.
type AppInfoBranding struct {
	// Category corresponds to the JSON schema field "category".
	Category AppBrandingCategory `json:"category,omitempty"`

	// Developer corresponds to the JSON schema field "developer".
	Developer AppBrandingDeveloper `json:"developer,omitempty"`

	// IsDiscoverableApp corresponds to the JSON schema field "isDiscoverableApp".
	IsDiscoverableApp bool `json:"isDiscoverableApp"`

	// PrivacyPolicy corresponds to the JSON schema field "privacyPolicy".
	PrivacyPolicy AppBrandingPrivacyPolicy `json:"privacyPolicy,omitempty"`

	// TermsOfService corresponds to the JSON schema field "termsOfService".
	TermsOfService AppBrandingTermsOfService `json:"termsOfService,omitempty"`

	// Website corresponds to the JSON schema field "website".
	Website AppBrandingWebsite `json:"website,omitempty"`
}

type AppInfoDescription *string

type AppInfoDistributionChannel *string

type AppInfoInstallUrl *string

type AppInfoLabels map[string]string

type AppInfoLogoUrl *string

type AppInfoLogoUrlDark *string

// EXPERIMENTAL - notification emitted when the app list changes.
type AppListUpdatedNotification struct {
	// Data corresponds to the JSON schema field "data".
	Data []AppInfo `json:"data"`
}

type AppMetadata struct {
	// Categories corresponds to the JSON schema field "categories".
	Categories *AppMetadataCategories `json:"categories,omitempty"`

	// Developer corresponds to the JSON schema field "developer".
	Developer AppMetadataDeveloper `json:"developer,omitempty"`

	// FirstPartyRequiresInstall corresponds to the JSON schema field
	// "firstPartyRequiresInstall".
	FirstPartyRequiresInstall AppMetadataFirstPartyRequiresInstall `json:"firstPartyRequiresInstall,omitempty"`

	// FirstPartyType corresponds to the JSON schema field "firstPartyType".
	FirstPartyType AppMetadataFirstPartyType `json:"firstPartyType,omitempty"`

	// Review corresponds to the JSON schema field "review".
	Review *AppMetadataReview `json:"review,omitempty"`

	// Screenshots corresponds to the JSON schema field "screenshots".
	Screenshots *AppMetadataScreenshots `json:"screenshots,omitempty"`

	// SeoDescription corresponds to the JSON schema field "seoDescription".
	SeoDescription AppMetadataSeoDescription `json:"seoDescription,omitempty"`

	// ShowInComposerWhenUnlinked corresponds to the JSON schema field
	// "showInComposerWhenUnlinked".
	ShowInComposerWhenUnlinked AppMetadataShowInComposerWhenUnlinked `json:"showInComposerWhenUnlinked,omitempty"`

	// SubCategories corresponds to the JSON schema field "subCategories".
	SubCategories *AppMetadataSubCategories `json:"subCategories,omitempty"`

	// Version corresponds to the JSON schema field "version".
	Version AppMetadataVersion `json:"version,omitempty"`

	// VersionId corresponds to the JSON schema field "versionId".
	VersionId AppMetadataVersionId `json:"versionId,omitempty"`

	// VersionNotes corresponds to the JSON schema field "versionNotes".
	VersionNotes AppMetadataVersionNotes `json:"versionNotes,omitempty"`
}

type AppMetadataCategories []string

type AppMetadataDeveloper *string

type AppMetadataFirstPartyRequiresInstall *bool

type AppMetadataFirstPartyType *string

type AppMetadataReview struct {
	// Status corresponds to the JSON schema field "status".
	Status string `json:"status"`
}

type AppMetadataScreenshots []AppScreenshot

type AppMetadataSeoDescription *string

type AppMetadataShowInComposerWhenUnlinked *bool

type AppMetadataSubCategories []string

type AppMetadataVersion *string

type AppInfoBranding_0 = AppBranding

type AppMetadataVersionNotes *string

type AppInfoAppMetadataReview_0 = AppReview

type AppInfoAppMetadata_0 = AppMetadata

type AppMetadataVersionId *string

type AppScreenshot struct {
	// FileId corresponds to the JSON schema field "fileId".
	FileId AppScreenshotFileId `json:"fileId,omitempty"`

	// Url corresponds to the JSON schema field "url".
	Url AppScreenshotUrl `json:"url,omitempty"`

	// UserPrompt corresponds to the JSON schema field "userPrompt".
	UserPrompt string `json:"userPrompt"`
}

type AppScreenshotFileId *string

type AppScreenshotUrl *string

type AppMetadataReview_0 = AppReview

type AppReview struct {
	// Status corresponds to the JSON schema field "status".
	Status string `json:"status"`
}
