// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package reasoning_text_delta_notification

type ReasoningTextDeltaNotification struct {
	// ContentIndex corresponds to the JSON schema field "contentIndex".
	ContentIndex int `json:"contentIndex"`

	// Delta corresponds to the JSON schema field "delta".
	Delta string `json:"delta"`

	// ItemId corresponds to the JSON schema field "itemId".
	ItemId string `json:"itemId"`

	// ThreadId corresponds to the JSON schema field "threadId".
	ThreadId string `json:"threadId"`

	// TurnId corresponds to the JSON schema field "turnId".
	TurnId string `json:"turnId"`
}
