// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package apply_patch_approval_response

type ApplyPatchApprovalResponse struct {
	// Decision corresponds to the JSON schema field "decision".
	Decision ReviewDecision `json:"decision"`
}

// User's decision in response to an ExecApprovalRequest.
type ReviewDecision interface{}
