// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package command_execution_request_approval_response

type CommandExecutionApprovalDecision interface{}

type CommandExecutionRequestApprovalResponse struct {
	// Decision corresponds to the JSON schema field "decision".
	Decision CommandExecutionApprovalDecision `json:"decision"`
}
