// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package thread_read_params

type ThreadReadParams struct {
	// When true, include turns and their items from rollout history.
	IncludeTurns bool `json:"includeTurns,omitempty"`

	// ThreadId corresponds to the JSON schema field "threadId".
	ThreadId string `json:"threadId"`
}
