// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package chatgpt_auth_tokens_refresh_response

type ChatgptAuthTokensRefreshResponse struct {
	// AccessToken corresponds to the JSON schema field "accessToken".
	AccessToken string `json:"accessToken"`

	// ChatgptAccountId corresponds to the JSON schema field "chatgptAccountId".
	ChatgptAccountId string `json:"chatgptAccountId"`

	// ChatgptPlanType corresponds to the JSON schema field "chatgptPlanType".
	ChatgptPlanType ChatgptAuthTokensRefreshResponseChatgptPlanType `json:"chatgptPlanType,omitempty"`
}

type ChatgptAuthTokensRefreshResponseChatgptPlanType *string
