// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package review_start_params

type ReviewDelivery string

const ReviewDeliveryDetached ReviewDelivery = "detached"
const ReviewDeliveryInline ReviewDelivery = "inline"

type ReviewTarget interface{}

type ReviewStartParamsDelivery_0 = ReviewDelivery

type ReviewStartParams struct {
	// Where to run the review: inline (default) on the current thread or detached on
	// a new thread (returned in `reviewThreadId`).
	Delivery interface{} `json:"delivery,omitempty"`

	// Target corresponds to the JSON schema field "target".
	Target ReviewTarget `json:"target"`

	// ThreadId corresponds to the JSON schema field "threadId".
	ThreadId string `json:"threadId"`
}
