// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package thread_loaded_list_params

type ThreadLoadedListParams struct {
	// Opaque pagination cursor returned by a previous call.
	Cursor ThreadLoadedListParamsCursor `json:"cursor,omitempty"`

	// Optional page size; defaults to no limit.
	Limit ThreadLoadedListParamsLimit `json:"limit,omitempty"`
}

// Opaque pagination cursor returned by a previous call.
type ThreadLoadedListParamsCursor *string

// Optional page size; defaults to no limit.
type ThreadLoadedListParamsLimit *int
