// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package context_compacted_notification

// Deprecated: Use `ContextCompaction` item type instead.
type ContextCompactedNotification struct {
	// ThreadId corresponds to the JSON schema field "threadId".
	ThreadId string `json:"threadId"`

	// TurnId corresponds to the JSON schema field "turnId".
	TurnId string `json:"turnId"`
}
