// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package mcp_server_oauth_login_completed_notification

type McpServerOauthLoginCompletedNotification struct {
	// Error corresponds to the JSON schema field "error".
	Error McpServerOauthLoginCompletedNotificationError `json:"error,omitempty"`

	// Name corresponds to the JSON schema field "name".
	Name string `json:"name"`

	// Success corresponds to the JSON schema field "success".
	Success bool `json:"success"`
}

type McpServerOauthLoginCompletedNotificationError *string
