// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package thread_token_usage_updated_notification

type ThreadTokenUsage struct {
	// Last corresponds to the JSON schema field "last".
	Last TokenUsageBreakdown `json:"last"`

	// ModelContextWindow corresponds to the JSON schema field "modelContextWindow".
	ModelContextWindow ThreadTokenUsageModelContextWindow `json:"modelContextWindow,omitempty"`

	// Total corresponds to the JSON schema field "total".
	Total TokenUsageBreakdown `json:"total"`
}

type ThreadTokenUsageModelContextWindow *int

type ThreadTokenUsageUpdatedNotification struct {
	// ThreadId corresponds to the JSON schema field "threadId".
	ThreadId string `json:"threadId"`

	// TokenUsage corresponds to the JSON schema field "tokenUsage".
	TokenUsage ThreadTokenUsage `json:"tokenUsage"`

	// TurnId corresponds to the JSON schema field "turnId".
	TurnId string `json:"turnId"`
}

type TokenUsageBreakdown struct {
	// CachedInputTokens corresponds to the JSON schema field "cachedInputTokens".
	CachedInputTokens int `json:"cachedInputTokens"`

	// InputTokens corresponds to the JSON schema field "inputTokens".
	InputTokens int `json:"inputTokens"`

	// OutputTokens corresponds to the JSON schema field "outputTokens".
	OutputTokens int `json:"outputTokens"`

	// ReasoningOutputTokens corresponds to the JSON schema field
	// "reasoningOutputTokens".
	ReasoningOutputTokens int `json:"reasoningOutputTokens"`

	// TotalTokens corresponds to the JSON schema field "totalTokens".
	TotalTokens int `json:"totalTokens"`
}
