// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package model_list_params

type ModelListParams struct {
	// Opaque pagination cursor returned by a previous call.
	Cursor ModelListParamsCursor `json:"cursor,omitempty"`

	// When true, include models that are hidden from the default picker list.
	IncludeHidden ModelListParamsIncludeHidden `json:"includeHidden,omitempty"`

	// Optional page size; defaults to a reasonable server-side value.
	Limit ModelListParamsLimit `json:"limit,omitempty"`
}

// Opaque pagination cursor returned by a previous call.
type ModelListParamsCursor *string

// When true, include models that are hidden from the default picker list.
type ModelListParamsIncludeHidden *bool

// Optional page size; defaults to a reasonable server-side value.
type ModelListParamsLimit *int
