// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package skills_config_write_params

type SkillsConfigWriteParams struct {
	// Enabled corresponds to the JSON schema field "enabled".
	Enabled bool `json:"enabled"`

	// Path corresponds to the JSON schema field "path".
	Path string `json:"path"`
}
