// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package mcp_server_oauth_login_params

type McpServerOauthLoginParams struct {
	// Name corresponds to the JSON schema field "name".
	Name string `json:"name"`

	// Scopes corresponds to the JSON schema field "scopes".
	Scopes *McpServerOauthLoginParamsScopes `json:"scopes,omitempty"`

	// TimeoutSecs corresponds to the JSON schema field "timeoutSecs".
	TimeoutSecs McpServerOauthLoginParamsTimeoutSecs `json:"timeoutSecs,omitempty"`
}

type McpServerOauthLoginParamsScopes []string

type McpServerOauthLoginParamsTimeoutSecs *int
