// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package config_requirements_read_response

type AskForApproval string

const AskForApprovalNever AskForApproval = "never"
const AskForApprovalOnFailure AskForApproval = "on-failure"
const AskForApprovalOnRequest AskForApproval = "on-request"
const AskForApprovalUntrusted AskForApproval = "untrusted"

type ConfigRequirements struct {
	// AllowedApprovalPolicies corresponds to the JSON schema field
	// "allowedApprovalPolicies".
	AllowedApprovalPolicies *ConfigRequirementsAllowedApprovalPolicies `json:"allowedApprovalPolicies,omitempty"`

	// AllowedSandboxModes corresponds to the JSON schema field "allowedSandboxModes".
	AllowedSandboxModes *ConfigRequirementsAllowedSandboxModes `json:"allowedSandboxModes,omitempty"`

	// AllowedWebSearchModes corresponds to the JSON schema field
	// "allowedWebSearchModes".
	AllowedWebSearchModes *ConfigRequirementsAllowedWebSearchModes `json:"allowedWebSearchModes,omitempty"`

	// EnforceResidency corresponds to the JSON schema field "enforceResidency".
	EnforceResidency interface{} `json:"enforceResidency,omitempty"`
}

type ConfigRequirementsAllowedApprovalPolicies []AskForApproval

type ConfigRequirementsAllowedSandboxModes []SandboxMode

type ConfigRequirementsAllowedWebSearchModes []WebSearchMode

type ConfigRequirementsReadResponse struct {
	// Null if no requirements are configured (e.g. no requirements.toml/MDM entries).
	Requirements *ConfigRequirementsReadResponseRequirements `json:"requirements,omitempty"`
}

// Null if no requirements are configured (e.g. no requirements.toml/MDM entries).
type ConfigRequirementsReadResponseRequirements struct {
	// AllowedApprovalPolicies corresponds to the JSON schema field
	// "allowedApprovalPolicies".
	AllowedApprovalPolicies *ConfigRequirementsAllowedApprovalPolicies `json:"allowedApprovalPolicies,omitempty"`

	// AllowedSandboxModes corresponds to the JSON schema field "allowedSandboxModes".
	AllowedSandboxModes *ConfigRequirementsAllowedSandboxModes `json:"allowedSandboxModes,omitempty"`

	// AllowedWebSearchModes corresponds to the JSON schema field
	// "allowedWebSearchModes".
	AllowedWebSearchModes *ConfigRequirementsAllowedWebSearchModes `json:"allowedWebSearchModes,omitempty"`

	// EnforceResidency corresponds to the JSON schema field "enforceResidency".
	EnforceResidency interface{} `json:"enforceResidency,omitempty"`
}

type NetworkRequirements struct {
	// AllowLocalBinding corresponds to the JSON schema field "allowLocalBinding".
	AllowLocalBinding NetworkRequirementsAllowLocalBinding `json:"allowLocalBinding,omitempty"`

	// AllowUnixSockets corresponds to the JSON schema field "allowUnixSockets".
	AllowUnixSockets *NetworkRequirementsAllowUnixSockets `json:"allowUnixSockets,omitempty"`

	// AllowUpstreamProxy corresponds to the JSON schema field "allowUpstreamProxy".
	AllowUpstreamProxy NetworkRequirementsAllowUpstreamProxy `json:"allowUpstreamProxy,omitempty"`

	// AllowedDomains corresponds to the JSON schema field "allowedDomains".
	AllowedDomains *NetworkRequirementsAllowedDomains `json:"allowedDomains,omitempty"`

	// DangerouslyAllowNonLoopbackAdmin corresponds to the JSON schema field
	// "dangerouslyAllowNonLoopbackAdmin".
	DangerouslyAllowNonLoopbackAdmin NetworkRequirementsDangerouslyAllowNonLoopbackAdmin `json:"dangerouslyAllowNonLoopbackAdmin,omitempty"`

	// DangerouslyAllowNonLoopbackProxy corresponds to the JSON schema field
	// "dangerouslyAllowNonLoopbackProxy".
	DangerouslyAllowNonLoopbackProxy NetworkRequirementsDangerouslyAllowNonLoopbackProxy `json:"dangerouslyAllowNonLoopbackProxy,omitempty"`

	// DeniedDomains corresponds to the JSON schema field "deniedDomains".
	DeniedDomains *NetworkRequirementsDeniedDomains `json:"deniedDomains,omitempty"`

	// Enabled corresponds to the JSON schema field "enabled".
	Enabled NetworkRequirementsEnabled `json:"enabled,omitempty"`

	// HttpPort corresponds to the JSON schema field "httpPort".
	HttpPort NetworkRequirementsHttpPort `json:"httpPort,omitempty"`

	// SocksPort corresponds to the JSON schema field "socksPort".
	SocksPort NetworkRequirementsSocksPort `json:"socksPort,omitempty"`
}

type NetworkRequirementsAllowLocalBinding *bool

type NetworkRequirementsAllowUnixSockets []string

type NetworkRequirementsAllowUpstreamProxy *bool

type NetworkRequirementsAllowedDomains []string

type NetworkRequirementsDangerouslyAllowNonLoopbackAdmin *bool

type NetworkRequirementsDangerouslyAllowNonLoopbackProxy *bool

type NetworkRequirementsDeniedDomains []string

type NetworkRequirementsEnabled *bool

type NetworkRequirementsHttpPort *int

type NetworkRequirementsSocksPort *int

type ResidencyRequirement string

type ConfigRequirementsEnforceResidency_0 = ResidencyRequirement

const ResidencyRequirementUs ResidencyRequirement = "us"
const SandboxModeDangerFullAccess SandboxMode = "danger-full-access"
const SandboxModeWorkspaceWrite SandboxMode = "workspace-write"

type WebSearchMode string

const WebSearchModeCached WebSearchMode = "cached"
const WebSearchModeDisabled WebSearchMode = "disabled"
const WebSearchModeLive WebSearchMode = "live"

type ConfigRequirementsReadResponseRequirements_0 = ConfigRequirements

type ConfigRequirementsReadResponseRequirementsEnforceResidency_0 = ResidencyRequirement

type SandboxMode string

const SandboxModeReadOnly SandboxMode = "read-only"
