// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package dynamic_tool_call_response

type DynamicToolCallOutputContentItem interface{}

type DynamicToolCallResponse struct {
	// ContentItems corresponds to the JSON schema field "contentItems".
	ContentItems []DynamicToolCallOutputContentItem `json:"contentItems"`

	// Success corresponds to the JSON schema field "success".
	Success bool `json:"success"`
}
