// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package skills_config_write_response

type SkillsConfigWriteResponse struct {
	// EffectiveEnabled corresponds to the JSON schema field "effectiveEnabled".
	EffectiveEnabled bool `json:"effectiveEnabled"`
}
