// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package thread_fork_params

type AskForApproval string

const AskForApprovalNever AskForApproval = "never"
const AskForApprovalOnFailure AskForApproval = "on-failure"
const AskForApprovalOnRequest AskForApproval = "on-request"
const AskForApprovalUntrusted AskForApproval = "untrusted"

type SandboxMode string

const SandboxModeDangerFullAccess SandboxMode = "danger-full-access"
const SandboxModeReadOnly SandboxMode = "read-only"
const SandboxModeWorkspaceWrite SandboxMode = "workspace-write"

type ThreadForkParamsApprovalPolicy_0 = AskForApproval

type ThreadForkParamsBaseInstructions *string

type ThreadForkParamsConfig map[string]interface{}

type ThreadForkParamsCwd *string

type ThreadForkParamsDeveloperInstructions *string

// Configuration overrides for the forked thread, if any.
type ThreadForkParamsModel *string

type ThreadForkParamsModelProvider *string

type ThreadForkParamsSandbox_0 = SandboxMode

// There are two ways to fork a thread: 1. By thread_id: load the thread from disk
// by thread_id and fork it into a new thread. 2. By path: load the thread from
// disk by path and fork it into a new thread.
//
// If using path, the thread_id param will be ignored.
//
// Prefer using thread_id whenever possible.
type ThreadForkParams struct {
	// ApprovalPolicy corresponds to the JSON schema field "approvalPolicy".
	ApprovalPolicy interface{} `json:"approvalPolicy,omitempty"`

	// BaseInstructions corresponds to the JSON schema field "baseInstructions".
	BaseInstructions ThreadForkParamsBaseInstructions `json:"baseInstructions,omitempty"`

	// Config corresponds to the JSON schema field "config".
	Config *ThreadForkParamsConfig `json:"config,omitempty"`

	// Cwd corresponds to the JSON schema field "cwd".
	Cwd ThreadForkParamsCwd `json:"cwd,omitempty"`

	// DeveloperInstructions corresponds to the JSON schema field
	// "developerInstructions".
	DeveloperInstructions ThreadForkParamsDeveloperInstructions `json:"developerInstructions,omitempty"`

	// Configuration overrides for the forked thread, if any.
	Model ThreadForkParamsModel `json:"model,omitempty"`

	// ModelProvider corresponds to the JSON schema field "modelProvider".
	ModelProvider ThreadForkParamsModelProvider `json:"modelProvider,omitempty"`

	// Sandbox corresponds to the JSON schema field "sandbox".
	Sandbox interface{} `json:"sandbox,omitempty"`

	// ThreadId corresponds to the JSON schema field "threadId".
	ThreadId string `json:"threadId"`
}
