// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package experimental_feature_list_response

type ExperimentalFeature struct {
	// Announcement copy shown to users when the feature is introduced. Null when this
	// feature is not in beta.
	Announcement ExperimentalFeatureAnnouncement `json:"announcement,omitempty"`

	// Whether this feature is enabled by default.
	DefaultEnabled bool `json:"defaultEnabled"`

	// Short summary describing what the feature does. Null when this feature is not
	// in beta.
	Description ExperimentalFeatureDescription `json:"description,omitempty"`

	// User-facing display name shown in the experimental features UI. Null when this
	// feature is not in beta.
	DisplayName ExperimentalFeatureDisplayName `json:"displayName,omitempty"`

	// Whether this feature is currently enabled in the loaded config.
	Enabled bool `json:"enabled"`

	// Stable key used in config.toml and CLI flag toggles.
	Name string `json:"name"`

	// Lifecycle stage of this feature flag.
	Stage interface{} `json:"stage"`
}

// Announcement copy shown to users when the feature is introduced. Null when this
// feature is not in beta.
type ExperimentalFeatureAnnouncement *string

// Short summary describing what the feature does. Null when this feature is not in
// beta.
type ExperimentalFeatureDescription *string

// User-facing display name shown in the experimental features UI. Null when this
// feature is not in beta.
type ExperimentalFeatureDisplayName *string

type ExperimentalFeatureListResponse struct {
	// Data corresponds to the JSON schema field "data".
	Data []ExperimentalFeature `json:"data"`

	// Opaque cursor to pass to the next call to continue after the last item. If
	// None, there are no more items to return.
	NextCursor ExperimentalFeatureListResponseNextCursor `json:"nextCursor,omitempty"`
}

// Opaque cursor to pass to the next call to continue after the last item. If None,
// there are no more items to return.
type ExperimentalFeatureListResponseNextCursor *string

type ExperimentalFeatureStage interface{}
