// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package thread_start_params

type AskForApproval string

const AskForApprovalNever AskForApproval = "never"
const AskForApprovalOnFailure AskForApproval = "on-failure"
const AskForApprovalOnRequest AskForApproval = "on-request"
const AskForApprovalUntrusted AskForApproval = "untrusted"

type DynamicToolSpec struct {
	// Description corresponds to the JSON schema field "description".
	Description string `json:"description"`

	// InputSchema corresponds to the JSON schema field "inputSchema".
	InputSchema interface{} `json:"inputSchema"`

	// Name corresponds to the JSON schema field "name".
	Name string `json:"name"`
}

type Personality string

const PersonalityFriendly Personality = "friendly"
const PersonalityNone Personality = "none"
const PersonalityPragmatic Personality = "pragmatic"

type SandboxMode string

const SandboxModeDangerFullAccess SandboxMode = "danger-full-access"
const SandboxModeReadOnly SandboxMode = "read-only"
const SandboxModeWorkspaceWrite SandboxMode = "workspace-write"

type ThreadStartParamsApprovalPolicy_0 = AskForApproval

type ThreadStartParamsBaseInstructions *string

type ThreadStartParamsConfig map[string]interface{}

type ThreadStartParamsCwd *string

type ThreadStartParamsDeveloperInstructions *string

type ThreadStartParamsEphemeral *bool

type ThreadStartParamsModel *string

type ThreadStartParamsModelProvider *string

type ThreadStartParamsPersonality_0 = Personality

type ThreadStartParamsSandbox_0 = SandboxMode

type ThreadStartParams struct {
	// ApprovalPolicy corresponds to the JSON schema field "approvalPolicy".
	ApprovalPolicy interface{} `json:"approvalPolicy,omitempty"`

	// BaseInstructions corresponds to the JSON schema field "baseInstructions".
	BaseInstructions ThreadStartParamsBaseInstructions `json:"baseInstructions,omitempty"`

	// Config corresponds to the JSON schema field "config".
	Config *ThreadStartParamsConfig `json:"config,omitempty"`

	// Cwd corresponds to the JSON schema field "cwd".
	Cwd ThreadStartParamsCwd `json:"cwd,omitempty"`

	// DeveloperInstructions corresponds to the JSON schema field
	// "developerInstructions".
	DeveloperInstructions ThreadStartParamsDeveloperInstructions `json:"developerInstructions,omitempty"`

	// Ephemeral corresponds to the JSON schema field "ephemeral".
	Ephemeral ThreadStartParamsEphemeral `json:"ephemeral,omitempty"`

	// Model corresponds to the JSON schema field "model".
	Model ThreadStartParamsModel `json:"model,omitempty"`

	// ModelProvider corresponds to the JSON schema field "modelProvider".
	ModelProvider ThreadStartParamsModelProvider `json:"modelProvider,omitempty"`

	// Personality corresponds to the JSON schema field "personality".
	Personality interface{} `json:"personality,omitempty"`

	// Sandbox corresponds to the JSON schema field "sandbox".
	Sandbox interface{} `json:"sandbox,omitempty"`
}
