// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package thread_unarchived_notification

type ThreadUnarchivedNotification struct {
	// ThreadId corresponds to the JSON schema field "threadId".
	ThreadId string `json:"threadId"`
}
