// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package skills_remote_write_params

type SkillsRemoteWriteParams struct {
	// HazelnutId corresponds to the JSON schema field "hazelnutId".
	HazelnutId string `json:"hazelnutId"`
}
