// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package thread_unarchive_params

type ThreadUnarchiveParams struct {
	// ThreadId corresponds to the JSON schema field "threadId".
	ThreadId string `json:"threadId"`
}
