// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package jsonrpc_error_error

type JSONRPCErrorError struct {
	// Code corresponds to the JSON schema field "code".
	Code int `json:"code"`

	// Data corresponds to the JSON schema field "data".
	Data interface{} `json:"data,omitempty"`

	// Message corresponds to the JSON schema field "message".
	Message string `json:"message"`
}
