// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package tool_request_user_input_params

// EXPERIMENTAL. Defines a single selectable option for request_user_input.
type ToolRequestUserInputOption struct {
	// Description corresponds to the JSON schema field "description".
	Description string `json:"description"`

	// Label corresponds to the JSON schema field "label".
	Label string `json:"label"`
}

// EXPERIMENTAL. Params sent with a request_user_input event.
type ToolRequestUserInputParams struct {
	// ItemId corresponds to the JSON schema field "itemId".
	ItemId string `json:"itemId"`

	// Questions corresponds to the JSON schema field "questions".
	Questions []ToolRequestUserInputQuestion `json:"questions"`

	// ThreadId corresponds to the JSON schema field "threadId".
	ThreadId string `json:"threadId"`

	// TurnId corresponds to the JSON schema field "turnId".
	TurnId string `json:"turnId"`
}

// EXPERIMENTAL. Represents one request_user_input question and its required
// options.
type ToolRequestUserInputQuestion struct {
	// Header corresponds to the JSON schema field "header".
	Header string `json:"header"`

	// Id corresponds to the JSON schema field "id".
	Id string `json:"id"`

	// IsOther corresponds to the JSON schema field "isOther".
	IsOther bool `json:"isOther,omitempty"`

	// IsSecret corresponds to the JSON schema field "isSecret".
	IsSecret bool `json:"isSecret,omitempty"`

	// Options corresponds to the JSON schema field "options".
	Options *ToolRequestUserInputQuestionOptions `json:"options,omitempty"`

	// Question corresponds to the JSON schema field "question".
	Question string `json:"question"`
}

type ToolRequestUserInputQuestionOptions []ToolRequestUserInputOption
