// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package config_batch_write_params

type ConfigBatchWriteParams struct {
	// Edits corresponds to the JSON schema field "edits".
	Edits []ConfigEdit `json:"edits"`

	// ExpectedVersion corresponds to the JSON schema field "expectedVersion".
	ExpectedVersion ConfigBatchWriteParamsExpectedVersion `json:"expectedVersion,omitempty"`

	// Path to the config file to write; defaults to the user's `config.toml` when
	// omitted.
	FilePath ConfigBatchWriteParamsFilePath `json:"filePath,omitempty"`
}

type ConfigBatchWriteParamsExpectedVersion *string

// Path to the config file to write; defaults to the user's `config.toml` when
// omitted.
type ConfigBatchWriteParamsFilePath *string

type ConfigEdit struct {
	// KeyPath corresponds to the JSON schema field "keyPath".
	KeyPath string `json:"keyPath"`

	// MergeStrategy corresponds to the JSON schema field "mergeStrategy".
	MergeStrategy MergeStrategy `json:"mergeStrategy"`

	// Value corresponds to the JSON schema field "value".
	Value interface{} `json:"value"`
}

type MergeStrategy string

const MergeStrategyReplace MergeStrategy = "replace"
const MergeStrategyUpsert MergeStrategy = "upsert"
