// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package skills_remote_write_response

type SkillsRemoteWriteResponse struct {
	// Id corresponds to the JSON schema field "id".
	Id string `json:"id"`

	// Path corresponds to the JSON schema field "path".
	Path string `json:"path"`
}
