// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package jsonrpc_response

// A successful (non-error) response to a request.
type JSONRPCResponse struct {
	// Id corresponds to the JSON schema field "id".
	Id RequestId `json:"id"`

	// Result corresponds to the JSON schema field "result".
	Result interface{} `json:"result"`
}

type RequestId interface{}
